export const money = value => new Intl.NumberFormat('en-CA', { style: 'currency', currency: 'CAD', maximumFractionDigits: 0 }).format(value);
export const accounts = { Cash: 'Asset', 'Accounts receivable': 'Asset', 'Allowance for doubtful accounts': 'Asset', Inventory: 'Asset', Supplies: 'Asset', 'Prepaid insurance': 'Asset', Equipment: 'Asset', 'Accumulated depreciation': 'Asset', 'Accounts payable': 'Liability', 'Loan payable': 'Liability', 'Interest payable': 'Liability', 'Wages payable': 'Liability', 'Unearned revenue': 'Liability', 'HST payable': 'Liability', 'Payroll payable': 'Liability', 'Owner capital': 'Equity', 'Owner drawings': 'Equity', 'Income summary': 'Equity', Revenue: 'Revenue', 'Sales discounts': 'Revenue', 'Cost of goods sold': 'Expense', Rent: 'Expense', Wages: 'Expense', Utilities: 'Expense', 'Bank fees': 'Expense', 'Insurance expense': 'Expense', 'Supplies expense': 'Expense', 'Depreciation expense': 'Expense', 'Interest expense': 'Expense', 'Bad debt expense': 'Expense', 'Loss on disposal': 'Expense' };
export const line = (account, debit = 0, credit = 0, why) => ({ account, debit, credit, why });
export function summarize(transactions) {
  const balances = Object.fromEntries(Object.keys(accounts).map(a => [a, 0]));
  transactions.forEach(t => t.lines.forEach(l => { balances[l.account] = (balances[l.account] || 0) + l.debit - l.credit; }));
  const total = type => Object.entries(balances).filter(([a]) => accounts[a] === type).reduce((sum, [, n]) => sum + n, 0);
  const revenue = -total('Revenue'), expenses = total('Expense'), profit = revenue - expenses;
  return { balances, revenue, expenses, profit, assets: total('Asset'), liabilities: -total('Liability'), equity: -total('Equity') + profit, units: transactions.reduce((s, t) => s + (t.inventory_units || 0), 0) };
}
const event = (day, description, lines, cash_category = 'Operating', extra = {}) => ({ event_key: `day-${day}`, day, description, lines, cash_category, ...extra });
const cashIn = amount => line('Cash', amount, 0, `${money(amount)} landed in Maple’s bank account. Cash is an asset Maple owns, and it just grew — debit.`);
const cashOut = amount => line('Cash', 0, amount, `${money(amount)} left the bank. A shrinking asset is a credit — even though your bank statement calls this a “debit”, that is the bank’s point of view, not Maple’s.`);
export const businessEvents = [
  event(1, 'You invest $20,000 to open Maple Coffee.', [cashIn(20000),line('Owner capital',0,20000,'The $20,000 came from you, the owner — not from a customer and not from a lender. Owner capital records your claim on the business; it grows with a credit.')],'Financing',{software:'Tally: Receipt voucher → capital ledger. QuickBooks: Bank deposit → owner equity.'}),
  event(5, 'Roast Supply delivers 300 bags at $10 each on credit.', [line('Inventory',3000,0,'300 bags arrived that Maple owns and intends to sell. Inventory is an asset; more of it is a debit.'),line('Accounts payable',0,3000,'Roast Supply has not been paid. Maple owes $3,000, and a growing debt is a credit.')],'Operating',{inventory_units:300,party:'Roast Supply',software:'Tally: Purchase voucher with stock items. QuickBooks: Bill with inventory items.'}),
  event(10, 'Pay $2,000 for the first month’s rent.', [line('Rent',2000,0,'A month of space was used up and nothing lasting was gained. That makes rent an expense, and expenses are debited.'),cashOut(2000)]),
  event(15, 'Buy a $4,000 espresso machine with cash.', [line('Equipment',4000,0,'Maple now owns a machine it will use for years — a new asset. Assets grow with a debit, so this is one asset (cash) swapped for another (equipment). Nothing is an expense yet; the cost reaches profit slowly through depreciation.'),cashOut(4000)],'Investing'),
  event(20, 'Sell 100 bags for $2,500 in cash; they cost $1,000.', [cashIn(2500),line('Revenue',0,2500,'Maple earned $2,500 by handing over coffee. Revenue increases the owner’s claim on the business, so like equity it grows with a credit.'),line('Cost of goods sold',1000,0,'The 100 bags that left the shelf cost $1,000. That cost is now used up — an expense, debited.'),line('Inventory',0,1000,'100 bags are gone. Inventory is an asset shrinking — credit.')],'Operating',{inventory_units:-100}),
  event(25, 'Run payroll: $1,500 gross, $300 withheld, $1,200 paid.', [line('Wages',1500,0,'Staff earned $1,500 of work. The whole amount is Maple’s cost whether or not it reaches their pockets, so Wages is debited $1,500.'),line('Cash',0,1200,'Only the $1,200 net pay actually left the bank — credit that amount, not the gross.'),line('Payroll payable',0,300,'The $300 withheld belongs to the CRA. Maple is holding it temporarily, which is a debt — a liability, credited.')]),
  event(30, 'Invoice Cedar Studio $2,000 for 80 bags, due in 30 days.', [line('Accounts receivable',2000,0,'Cedar Studio owes Maple $2,000. A customer’s promise to pay is an asset (a receivable) — debit.'),line('Revenue',0,2000,'The bags were delivered, so the sale is earned today. Revenue is credited now even though no cash has arrived.'),line('Cost of goods sold',800,0,'80 bags at $10 each left the shelf — $800 of cost used up, debited.'),line('Inventory',0,800,'The 80 bags are gone — asset down, credit.')],'Operating',{inventory_units:-80,party:'Cedar Studio'}),
  event(35, 'Receive $1,000 against Cedar Studio’s invoice.', [cashIn(1000),line('Accounts receivable',0,1000,'Cedar now owes $1,000 less. The receivable shrinks — credit. No revenue here: that was recorded on Day 30 when the coffee was delivered.')],'Operating',{party:'Cedar Studio',software:'Tally: Receipt allocated against the bill. QuickBooks: Receive payment linked to the invoice. Do not create a second sale.'}),
  event(40, 'Pay Roast Supply $2,000 against its bill.', [line('Accounts payable',2000,0,'Maple owes Roast Supply $2,000 less. A liability shrinking is debited — this debit is not an expense; the inventory cost was recorded on Day 5.'),cashOut(2000)],'Operating',{party:'Roast Supply'}),
  event(45, 'The bank advances a $10,000 business loan.', [cashIn(10000),line('Loan payable',0,10000,'That money must be repaid. A new debt is a credit — and it is not revenue, because Maple did not earn it.')],'Financing'),
  event(50, 'Pay a $250 electricity bill.', [line('Utilities',250,0,'Electricity was consumed — a cost with no lasting asset, so an expense, debited.'),cashOut(250)]),
  event(55, 'Sell 40 bags for $1,000 plus $130 Ontario HST, paid now.', [line('Cash',1130,0,'Customers handed over $1,130 in total — debit Cash for the full amount that hit the bank.'),line('Revenue',0,1000,'Only $1,000 was earned by Maple; credit Revenue for that, not for $1,130.'),line('HST payable',0,130,'The $130 belongs to the CRA. Maple collected it on their behalf, so it is a liability, credited.'),line('Cost of goods sold',400,0,'40 bags × $10 = $400 of cost used up — debit.'),line('Inventory',0,400,'40 bags gone — asset down, credit.')],'Operating',{inventory_units:-40}),
  event(60, 'Buy another 100 bags for $1,000 on credit.', [line('Inventory',1000,0,'100 more bags now owned — asset up, debit.'),line('Accounts payable',0,1000,'Bought on credit means owed, not paid. The liability grows — credit.')],'Operating',{inventory_units:100,party:'Roast Supply'}),
  event(65, 'Cedar returns 10 unopened bags: credit $250 and restock $100.', [line('Revenue',250,0,'Ten bags came back, so $250 of the Day 30 sale is undone. Revenue normally sits on the credit side; reducing it takes a debit.'),line('Accounts receivable',0,250,'Cedar owes $250 less — receivable down, credit.'),line('Inventory',100,0,'The ten unopened bags are back on the shelf — asset up, debit $100: their cost, not their selling price.'),line('Cost of goods sold',0,100,'Those bags were never really sold, so $100 of cost comes back out of COGS — credit.')],'Operating',{inventory_units:10,party:'Cedar Studio'}),
  event(70, 'Refund $125 for 5 returned bags from the tax-free cash sale.', [line('Revenue',125,0,'Five bags returned; $125 of revenue is reversed with a debit.'),cashOut(125),line('Inventory',50,0,'Five bags back in stock at their $10 cost — asset up, debit $50.'),line('Cost of goods sold',0,50,'$50 of cost was never truly consumed — take it back out of COGS with a credit.')],'Operating',{inventory_units:5}),
  event(75, 'Find an unrecorded $35 bank service fee.', [line('Bank fees',35,0,'A service the bank charged for — an expense, debited. Discovered late, but recorded the same way as any payment.'),cashOut(35)]),
  event(80, 'Remit the $300 payroll withholding liability.', [line('Payroll payable',300,0,'Maple no longer holds the $300 for the CRA — liability down, debit. Not an expense: the wages cost was recorded on Day 25.'),cashOut(300)]),
  event(90, 'Pay the $130 HST balance to the tax authority.', [line('HST payable',130,0,'The tax Maple collected is handed over — the liability is settled with a debit. Revenue is untouched.'),cashOut(130)])
];
export const curriculum = [
 ['What is accounting actually doing?', 'Build your transaction intuition', 'equipment'], ['Think like an accountant', 'Journals, ledgers & double entry', 'capital'], ['Follow one dollar', 'From a sale to your statements', 'invoice'], ['The three financial statements', 'Profit is not the same as cash', 'collection'], ['The accounting cycle', 'From source documents to closing', 'rent'], ['Receivables & payables', 'Track who owes whom', 'collection'], ['Bank reconciliation', 'Make the bank and books agree', 'bank'], ['Inventory', 'Follow the cost, not just the stock', 'inventory'], ['GST/HST & sales tax', 'Separate your revenue from tax', 'tax'], ['Payroll', 'Gross pay, net pay & liabilities', 'payroll'], ['Fix the books', 'Investigate before you correct', 'bank'], ['Adjusting entries', 'Prepaid, accrued, unearned & supplies', 'prepaid'], ['Long-term assets', 'Depreciation, book value & disposal', 'depreciation'], ['Credit losses & discounts', 'Allowances and early-payment terms', 'baddebt'], ['Inventory costing', 'FIFO vs weighted average', 'fifo'], ['Closing the books', 'Drawings, closing entries & equity', 'closing'], ['Tally mode', 'Think in ledgers and vouchers', 'equipment'], ['QuickBooks mode', 'Understand the accounting underneath', 'invoice']
];