const dr = (account, amount, why) => ({ account, debit: amount, credit: 0, why });
const cr = (account, amount, why) => ({ account, debit: 0, credit: amount, why });
export const advancedLessons = [
 { id:'prepaid', level:'Intermediate', short:'Prepaid insurance', title:'Paying early is not spending', topic:'Adjusting Entries',
  scenario:'On January 1 Maple pays $6,000 cash for a 12-month insurance policy. Which TWO changes happen today?',
  options:['Cash decreases $6,000','Insurance expense increases $6,000','Prepaid insurance increases $6,000','Insurance expense increases $500'], correct:[0,2],
  optionNotes:['Cash decreases $6,000: yes — the premium left the bank.','Insurance expense $6,000: no — none of the coverage has been used yet.','Prepaid insurance $6,000: yes — twelve months of coverage is a resource Maple owns.','Insurance expense $500: no — that adjustment comes at the end of January, not today.'],
  explanation:'Maple bought twelve months of future protection. Until each month passes, that protection is still owned — an asset called Prepaid insurance. Cash falls; there is no expense yet.',
  principle:'Expenses are recognized when the benefit is used up, not when cash is paid. Paying ahead creates an asset that is expensed month by month.',
  intuition:'Paying $6,000 feels like a $6,000 expense — the money is gone. But Maple traded cash for a year of coverage it still holds, the same way it traded cash for a machine. Only as each month passes does $500 of it get used up. On payment day, nothing has been consumed.',
  journal:[dr('Prepaid insurance',6000,'Maple now owns a year of coverage — an asset, debited.'),cr('Cash',6000,'The premium left the bank — asset down, credit.')],
  impact:['Cash −$6,000','Prepaid insurance +$6,000','Profit unchanged today'],
  tally:'Payment voucher → Prepaid Insurance (current asset) and bank. A monthly journal voucher moves $500 to Insurance expense.', quickbooks:'Expense → categorize to a Prepaid Insurance other-current-asset account. Recurring monthly journal entry: debit Insurance expense, credit Prepaid insurance.',
  problem:'January profit collapsed because the full annual premium was expensed in one month.',
  transfer:{question:'It is now January 31. What adjusting entry is needed?',options:['Debit Insurance expense $500, credit Prepaid insurance $500','Debit Insurance expense $6,000, credit Cash $6,000','No entry — the cash already went out'],correct:0,why:'One of the twelve months has been used. $500 moves from the asset to expense. Cash is untouched — it moved on January 1.'} },
 { id:'accrued', level:'Intermediate', short:'Accrued wages', title:'Wages earned, not yet paid', topic:'Adjusting Entries',
  scenario:'It is month-end. Staff worked the last three days ($900) but payday is next week. Which TWO changes are recorded now?',
  options:['Wages increases $900','Cash decreases $900','Wages payable increases $900','Nothing until payday'], correct:[0,2],
  optionNotes:['Wages $900: yes — three days of labour were consumed this month.','Cash: no — payday is next week; nothing has left the bank.','Wages payable $900: yes — Maple owes staff for work already done.','Nothing until payday: no — that would report this month’s profit too high.'],
  explanation:'The work happened this month, so its cost belongs to this month. No cash has moved, so the other side is a liability: Maple owes its staff.',
  principle:'Matching: record costs in the period the work is done, even if payment comes later. An accrued expense is an expense recorded before the cash leaves.',
  intuition:'It feels wrong to record payroll when nobody has been paid — nothing happened at the bank. But the employees have already done the work and Maple is already on the hook. Waiting for payday would shove this month’s cost into next month and overstate this month’s profit.',
  journal:[dr('Wages',900,'Three days of work were used this month — expense, debited now.'),cr('Wages payable',900,'Staff are owed $900 — a liability, credited until payday.')],
  impact:['Expenses +$900','Liabilities +$900','Cash unchanged'],
  tally:'Month-end journal voucher: Wages → Outstanding wages (current liability). Settle it on payday.', quickbooks:'Journal entry debiting Wages expense and crediting Accrued liabilities; the payday payment clears the liability.',
  problem:'Profit jumps and dips every other month because wages are only recorded when paid.',
  transfer:{question:'Payday arrives and the $900 is paid. What is debited?',options:['Wages expense','Wages payable','Cash'],correct:1,why:'The expense already sits in last month. Paying now just settles the debt: debit Wages payable, credit Cash.'} },
 { id:'unearned', level:'Intermediate', short:'Customer deposit', title:'Paid, but not yet earned', topic:'Adjusting Entries',
  scenario:'A customer pays $1,200 upfront for a 12-month coffee subscription. No coffee has shipped. Besides Cash, which TWO statements are true?',
  options:['Revenue increases $1,200','Unearned revenue increases $1,200','Revenue increases $0 today','Accounts receivable increases $1,200'], correct:[1,2],
  optionNotes:['Revenue $1,200: no — no coffee has been delivered, so nothing is earned yet.','Unearned revenue $1,200: yes — Maple owes the customer twelve deliveries.','Revenue $0 today: yes — earning happens month by month as coffee ships.','Accounts receivable: no — that is for customers who owe Maple; this customer already paid.'],
  explanation:'Maple holds $1,200 it has not earned. It owes the customer twelve deliveries — an obligation, so a liability. Revenue arrives one month at a time as coffee ships.',
  principle:'Revenue is recognized when the promise is fulfilled, not when cash is received. Cash received in advance is a liability called unearned (deferred) revenue.',
  intuition:'Money from a customer feels like the purest form of revenue. But Maple could still be asked to refund it — nothing has been delivered. Until the coffee ships, the $1,200 is a debt to the customer. That is how a cash receipt can create a liability instead of income.',
  journal:[dr('Cash',1200,'The money is in the bank — asset up, debit.'),cr('Unearned revenue',1200,'Maple owes the customer twelve months of coffee — an obligation, so a liability credited.')],
  impact:['Cash +$1,200','Liabilities +$1,200','Revenue unchanged today'],
  tally:'Receipt voucher → Advance from customers ledger (current liability). A monthly journal moves $100 to Sales.', quickbooks:'Receive the payment to an Unearned revenue liability account; a monthly journal entry recognizes $100 of revenue.',
  problem:'Revenue spiked in January and the client wonders why February looks empty despite deliveries.',
  transfer:{question:'After the first month’s coffee ships, what adjusting entry is made?',options:['Debit Unearned revenue $100, credit Revenue $100','Debit Cash $100, credit Revenue $100','Debit Revenue $100, credit Cash $100'],correct:0,why:'One twelfth of the promise is fulfilled. The liability shrinks by $100 and $100 of revenue is earned. Cash moved months ago.'} },
 { id:'supplies', level:'Intermediate', short:'Supplies used', title:'Count what is left', topic:'Adjusting Entries',
  scenario:'Maple bought $400 of cups and lids this month, recorded as Supplies (an asset). A month-end count shows $150 still on hand. Which TWO changes does the adjustment make?',
  options:['Supplies expense increases $250','Supplies expense increases $150','Supplies decreases $250','Cash decreases $250'], correct:[0,2],
  optionNotes:['Supplies expense $250: yes — the portion used up this month.','Supplies expense $150: no — $150 is what is still on the shelf.','Supplies decreases $250: yes — the asset falls to the counted $150.','Cash: no — cash moved when the supplies were bought, not at the count.'],
  explanation:'Started with $400, $150 remains, so $250 was used. The used portion leaves the asset and becomes expense. The count gives you the answer; the entry records it.',
  principle:'Assets that get consumed are expensed as they are used. When usage is not tracked item by item, a period-end count determines the expense.',
  intuition:'The natural guess is that the $150 you just counted is the expense — it is the number in front of you. But what you counted is what remains, which is still an asset. The expense is what disappeared: $400 − $150 = $250.',
  journal:[dr('Supplies expense',250,'Cups and lids worth $250 were used up — expense, debited.'),cr('Supplies',250,'The asset drops from $400 to the $150 actually on hand — credit $250.')],
  impact:['Expenses +$250','Assets −$250','Cash unchanged'],
  tally:'Journal voucher: Consumables expense → Stores & supplies asset ledger, based on the physical count.', quickbooks:'Journal entry debiting Supplies expense and crediting the Supplies asset account for the amount used.',
  problem:'Supplies expense is zero all year and then explodes in December.',
  transfer:{question:'Next month starts with $150 of supplies, $300 more are bought, and $120 remain at month-end. Supplies expense?',options:['$120','$330','$450'],correct:1,why:'Available = $150 + $300 = $450. Remaining = $120. Used = $330.'} },
 { id:'interest', level:'Intermediate', short:'Accrued interest', title:'The loan costs money every day', topic:'Adjusting Entries',
  scenario:'Maple’s $10,000 loan carries 6% annual interest, paid every quarter. One month has passed with no payment. Which TWO changes record the month?',
  options:['Interest expense increases $50','Interest expense increases $600','Interest payable increases $50','Loan payable increases $50'], correct:[0,2],
  optionNotes:['Interest expense $50: yes — one month of a $600 annual cost.','Interest expense $600: no — that is a whole year; only one month has passed.','Interest payable $50: yes — owed to the bank, separate from the principal.','Loan payable $50: no — interest is not new borrowing; the principal stays $10,000.'],
  explanation:'$10,000 × 6% ÷ 12 = $50 for the month. The cost has been incurred by using the money; the bank just hasn’t billed yet. So it is an expense now and a payable until paid.',
  principle:'Interest accrues with time. Record it in the period it is incurred — as an expense and a payable — regardless of the payment schedule.',
  intuition:'Nothing happened — no statement, no payment — so why record anything? Because Maple used the bank’s money for a month, and that use has a price. Skipping it would make this month look cheaper and the quarter-end month look expensive for no real reason.',
  journal:[dr('Interest expense',50,'One month of borrowing cost was incurred — expense, debited.'),cr('Interest payable',50,'Maple owes the bank $50 it hasn’t paid yet — a liability, credited.')],
  impact:['Expenses +$50','Liabilities +$50','Cash unchanged'],
  tally:'Month-end journal voucher: Interest on loan → Interest payable (current liability). A payment voucher settles it when paid.', quickbooks:'Recurring journal entry to Interest expense / Interest payable; the quarterly payment is split between Interest payable and any principal.',
  problem:'Interest expense shows $0 for two months and $150 in the third.',
  transfer:{question:'At quarter-end Maple pays $150 of interest. Which account is debited?',options:['Interest expense $150','Interest payable $150','Loan payable $150'],correct:1,why:'Three months of $50 have already been expensed. The payment clears the accumulated payable — debit Interest payable, credit Cash.'} },
 { id:'depreciation', level:'Intermediate', short:'Depreciation', title:'Spreading the machine’s cost', topic:'Long-term Assets',
  scenario:'The $4,000 espresso machine should last 5 years with no resale value. Year-end arrives. Which TWO changes record straight-line depreciation for the year?',
  options:['Depreciation expense increases $800','Equipment decreases $800 directly','Accumulated depreciation increases $800','Cash decreases $800'], correct:[0,2],
  optionNotes:['Depreciation expense $800: yes — one fifth of the cost belongs to this year.','Equipment decreases directly: no — the cost stays at $4,000; the reduction goes to a separate contra account.','Accumulated depreciation $800: yes — the running total of cost used up so far.','Cash: no — the cash was spent on Day 15; depreciation never touches cash.'],
  explanation:'$4,000 ÷ 5 years = $800 per year. That slice of the machine’s cost becomes expense. Instead of erasing it from Equipment, it piles up in Accumulated depreciation so the original cost stays visible.',
  principle:'Long-lived assets are expensed over their useful life. Accumulated depreciation is a contra-asset: it sits beside the asset and reduces it while preserving the historical cost.',
  intuition:'Two things feel odd. First, an expense with no cash — the cash left when the machine was bought. Second, a credit balance inside the asset section: Accumulated depreciation lives with assets but carries a credit, because its whole job is to subtract from Equipment. $4,000 − $800 = $3,200 net book value.',
  journal:[dr('Depreciation expense',800,'One year of the machine’s usefulness is consumed — expense, debited.'),cr('Accumulated depreciation',800,'A contra-asset: credited so it subtracts from Equipment without erasing the $4,000 cost.')],
  impact:['Expenses +$800','Net book value $3,200','Cash unchanged'],
  tally:'Journal voucher: Depreciation → Accumulated depreciation under the fixed asset group; Tally does not compute depreciation automatically.', quickbooks:'Journal entry: Depreciation expense / Accumulated depreciation (a fixed-asset contra account). Schedule it as a recurring entry.',
  problem:'The client says the machine still shows $4,000 on the balance sheet after three years.',
  transfer:{question:'After two full years, what is the machine’s net book value?',options:['$4,000','$2,400','$1,600'],correct:1,why:'Two years × $800 = $1,600 accumulated. $4,000 − $1,600 = $2,400. The Equipment account itself still reads $4,000.'} },
 { id:'disposal', level:'Advanced', short:'Asset disposal', title:'Selling a used machine', topic:'Long-term Assets',
  scenario:'After 3 years (accumulated depreciation $2,400), Maple sells the $4,000 machine for $1,000 cash. Which TWO statements are true?',
  options:['Maple records a $600 loss','Maple records a $3,000 loss','Equipment is credited for $4,000','Equipment is credited for $1,600'], correct:[0,2],
  optionNotes:['$600 loss: yes — $1,600 book value minus $1,000 cash.','$3,000 loss: no — $2,400 of the cost was already expensed in prior years.','Equipment credited $4,000: yes — the full original cost leaves the books.','Equipment credited $1,600: no — book value is a calculation, not a balance in any single account.'],
  explanation:'Book value is $4,000 − $2,400 = $1,600. Selling for $1,000 means a $600 loss. To remove the asset you must wipe out both its cost ($4,000) and its accumulated depreciation ($2,400).',
  principle:'On disposal, remove the asset’s cost and its accumulated depreciation. Proceeds minus book value is the gain or loss.',
  intuition:'Comparing $1,000 received to $4,000 paid suggests a $3,000 loss — but $2,400 of that was already expensed through depreciation. The real comparison is proceeds against book value. And notice: Accumulated depreciation is debited here, the one time a contra-asset takes a debit, because it is being cleared out.',
  journal:[dr('Cash',1000,'The buyer paid $1,000 — asset up, debit.'),dr('Accumulated depreciation',2400,'The contra-asset is cleared out with a debit; there is no machine left to depreciate.'),dr('Loss on disposal',600,'Book value $1,600 versus proceeds $1,000 — the $600 shortfall is a loss, debited like an expense.'),cr('Equipment',4000,'The machine’s original cost is removed — asset down, credit the full $4,000.')],
  impact:['Cash +$1,000','Equipment (net) −$1,600','Profit −$600'],
  tally:'Journal voucher clearing the asset and accumulated depreciation ledgers, with Loss on sale of asset for the difference; receipt voucher for the cash.', quickbooks:'Journal entry: debit Bank $1,000, debit Accumulated depreciation $2,400, debit Loss on disposal $600, credit Equipment $4,000.',
  problem:'The fixed asset was sold last year but still appears on the balance sheet, and depreciation keeps posting.',
  transfer:{question:'Same machine, but sold for $2,000 instead. Result?',options:['$400 gain','$2,000 loss','$400 loss'],correct:0,why:'Proceeds $2,000 exceed book value $1,600 by $400 — a gain, credited.'} },
 { id:'baddebt', level:'Advanced', short:'Bad debts', title:'Some customers won’t pay', topic:'AR/AP',
  scenario:'Year-end receivables are $10,000. Experience says about 2% will never be collected. Which TWO changes record this estimate?',
  options:['Bad debt expense increases $200','Accounts receivable decreases $200 directly','Allowance for doubtful accounts increases $200','Revenue decreases $200'], correct:[0,2],
  optionNotes:['Bad debt expense $200: yes — the expected cost of selling on credit this year.','AR decreases directly: no — you don’t know which customer yet; individual balances stay intact.','Allowance $200: yes — a contra-asset that reduces receivables to their expected collectible value.','Revenue decreases: no — the sales were real; the cost of not collecting is an expense.'],
  explanation:'Maple does not yet know which customer will fail, so it cannot reduce any specific receivable. It records the expected loss as an expense and parks the reduction in an allowance that sits against receivables.',
  principle:'The allowance method matches expected credit losses to the period of the sale. Allowance for doubtful accounts is a contra-asset; net receivables = AR − allowance.',
  intuition:'Recording a loss before anyone has actually defaulted feels like guessing. But waiting until a customer fails — maybe next year — would leave this year’s profit too high and this year’s receivables too rosy. The allowance shows the realistic number without touching any individual customer balance.',
  journal:[dr('Bad debt expense',200,'The expected cost of credit sales that won’t be collected — expense, debited this year.'),cr('Allowance for doubtful accounts',200,'A contra-asset credited to reduce receivables on the balance sheet without changing any customer’s ledger.')],
  impact:['Expenses +$200','Net receivables $9,800','Cash unchanged'],
  tally:'Journal voucher: Bad debts → Provision for doubtful debts (grouped per policy). Actual write-offs later hit the provision.', quickbooks:'Journal entry to Bad debt expense and an Allowance for doubtful accounts contra-AR account; actual write-offs use a credit memo with a bad-debt item.',
  problem:'A client’s receivables report shows $10,000 but they admit half of it is two years old.',
  transfer:{question:'In March, customer Oak Café ($150) is confirmed bankrupt. The write-off entry is:',options:['Debit Bad debt expense, credit Accounts receivable','Debit Allowance for doubtful accounts, credit Accounts receivable','Debit Revenue, credit Accounts receivable'],correct:1,why:'The expense was already estimated last year. The write-off uses up part of the allowance and removes Oak Café’s balance — no new expense.'} },
 { id:'discount', level:'Intermediate', short:'Sales discount', title:'Paying early earns a discount', topic:'AR/AP',
  scenario:'Cedar Studio pays a $1,000 invoice within 10 days and takes the 2% early-payment discount, sending $980. Besides Cash, which TWO changes happen?',
  options:['Accounts receivable decreases $980','Accounts receivable decreases $1,000','Sales discounts increases $20','Bank fees increases $20'], correct:[1,2],
  optionNotes:['AR decreases $980: no — that would leave a phantom $20 balance Cedar will never pay.','AR decreases $1,000: yes — the invoice is fully settled under its terms.','Sales discounts $20: yes — a contra-revenue account that reduces net sales.','Bank fees $20: no — the bank charged nothing; Maple chose to offer the discount.'],
  explanation:'The full $1,000 receivable is settled — Cedar owes nothing more. Maple received $980; the $20 given up is a reduction of revenue tracked in Sales discounts.',
  principle:'Settling a receivable clears its full amount. Discounts granted reduce net revenue through a contra-revenue account, keeping gross sales visible.',
  intuition:'Only $980 arrived, so it is tempting to reduce receivables by $980 and leave $20 hanging. But Cedar has fully paid under the terms — nobody owes anything. The $20 is the price of getting cash faster, and it belongs on the revenue side as a discount, not as a bank cost.',
  journal:[dr('Cash',980,'The $980 arrived in the bank — asset up, debit.'),dr('Sales discounts',20,'Revenue given up for early payment. It sits on the debit side because it reduces revenue, which is normally a credit.'),cr('Accounts receivable',1000,'Cedar’s full $1,000 obligation is cleared — receivable down, credit.')],
  impact:['Cash +$980','Receivables −$1,000','Net revenue −$20'],
  tally:'Receipt voucher against the bill with a Discount allowed ledger for the $20 so the bill closes fully.', quickbooks:'Receive payment for $980 and apply a $20 discount to the invoice (discount account = Sales discounts). The invoice closes.',
  problem:'Dozens of invoices show tiny unpaid balances of a few dollars each.',
  transfer:{question:'Maple pays its own $2,000 supplier bill early and gets a 1% discount. What is credited to Cash?',options:['$2,000','$1,980','$20'],correct:1,why:'Maple pays $1,980. Accounts payable is debited $2,000 (fully settled); the $20 saved is a purchase discount that reduces inventory cost or is recorded as income, depending on policy.'} },
 { id:'fifo', level:'Advanced', short:'FIFO costing', title:'Which bags did you sell?', topic:'Inventory',
  scenario:'Maple bought 100 bags at $10, then 100 more at $12. It then sells 150 bags. Using FIFO (first-in, first-out), which TWO statements are true?',
  options:['Cost of goods sold is $1,600','Cost of goods sold is $1,800','Ending inventory is $600','Ending inventory is $400'], correct:[0,2],
  optionNotes:['COGS $1,600: yes — the 100 cheapest bags first, then 50 at $12.','COGS $1,800: no — that would use 150 × $12, ignoring the older $10 bags.','Ending inventory $600: yes — 50 remaining bags at the newest $12 cost.','Ending inventory $400: no — $2,200 total cost − $1,600 COGS leaves $600.'],
  explanation:'FIFO assumes the oldest costs leave first: 100 × $10 + 50 × $12 = $1,600. The 50 bags left are the newest, at $12 = $600.',
  principle:'When identical goods are bought at different prices, a cost-flow assumption (FIFO, weighted average) decides which cost goes to COGS and which stays in inventory. Total cost is fixed; only the split changes.',
  intuition:'It seems like the sold bags should simply cost “$10 or $12” — but Maple sold 150 out of a mixed pile. FIFO is not about which physical bag went out; it is a rule for which cost to release first. When prices are rising, FIFO gives lower COGS and higher profit than weighted average.',
  journal:[dr('Cost of goods sold',1600,'The cost of the 150 bags released under FIFO — $1,000 + $600 — is used up, debited.'),cr('Inventory',1600,'Inventory falls from $2,200 to $600 — the asset shrinks by the FIFO cost, credit.')],
  impact:['Inventory −$1,600','COGS +$1,600','Ending stock $600 (50 bags)'],
  tally:'Stock valuation method is set per stock item (FIFO, Average, and others). Tally computes COGS from the chosen method.', quickbooks:'QuickBooks Online uses FIFO for inventory items and posts COGS automatically on each sale.',
  problem:'Two branches sell the same product but report different gross margins — one uses average cost, the other FIFO.',
  transfer:{question:'Same purchases, but using weighted average cost. COGS for 150 bags?',options:['$1,600','$1,650','$1,800'],correct:1,why:'Average cost = $2,200 ÷ 200 = $11. 150 × $11 = $1,650. Ending inventory = 50 × $11 = $550.'} },
 { id:'drawings', level:'Intermediate', short:'Owner drawings', title:'Your money, but not an expense', topic:'Closing & Equity',
  scenario:'You take $1,500 from Maple’s bank account to pay your personal rent. Which TWO changes happen in Maple’s books?',
  options:['Cash decreases $1,500','Rent expense increases $1,500','Owner drawings increases $1,500','Wages increases $1,500'], correct:[0,2],
  optionNotes:['Cash decreases $1,500: yes — the money left the business account.','Rent expense: no — the business did not rent anything; this is your personal cost.','Owner drawings $1,500: yes — a withdrawal that reduces your equity.','Wages: no — you are the owner, not an employee on payroll here.'],
  explanation:'The business paid nothing for itself — the owner took money out. That reduces the owner’s stake, tracked in Owner drawings. Profit is untouched.',
  principle:'The business is a separate entity from its owner. Withdrawals reduce equity directly and never appear on the income statement.',
  intuition:'You paid rent, so surely it is Rent expense? Not Maple’s rent. The business gained nothing; it handed its owner some of their own equity back. Drawings is debited because it reduces equity — a credit-side account — making it the mirror image of Owner capital.',
  journal:[dr('Owner drawings',1500,'A withdrawal reduces the owner’s equity. Equity is a credit-side account, so reducing it takes a debit.'),cr('Cash',1500,'Cash left the business — asset down, credit.')],
  impact:['Cash −$1,500','Equity −$1,500','Profit unchanged'],
  tally:'Payment voucher → Drawings ledger under Capital Account. Never an expense ledger.', quickbooks:'Expense or transfer categorized to Owner’s draw (equity), not to any expense category.',
  problem:'The owner’s personal purchases are inflating business expenses and shrinking taxable profit incorrectly.',
  transfer:{question:'A corporation pays its shareholder a $5,000 dividend. Which is closest in nature?',options:['A wage expense','An owner drawing','A loan repayment'],correct:1,why:'Dividends, like drawings, return equity to owners. They reduce retained earnings and never touch the income statement.'} },
 { id:'closing', level:'Advanced', short:'Closing entries', title:'Resetting the scoreboard', topic:'Closing & Equity',
  scenario:'Year-end. Revenue of $50,000 and expenses of $38,000 have been closed into Income summary, leaving a $12,000 credit balance. Which TWO happen when the books are closed?',
  options:['Net income of $12,000 moves into Owner capital','Cash increases $12,000','Revenue and expense accounts start next year at zero','Assets reset to zero'], correct:[0,2],
  optionNotes:['Net income → Owner capital: yes — profit permanently increases the owner’s claim.','Cash increases: no — closing entries never touch cash; profit is not a cash account.','Revenue and expenses reset: yes — they measure one period only.','Assets reset: no — balance sheet accounts carry forward.'],
  explanation:'Income statement accounts measure one period, so they are emptied at year-end. Their net result — the $12,000 profit — is transferred to Owner capital, where it belongs permanently. Balance sheet accounts carry on.',
  principle:'Temporary accounts (revenue, expenses, drawings) close to equity each period. Permanent accounts (assets, liabilities, equity) never close.',
  intuition:'People expect profit to be sitting somewhere as cash. It isn’t — profit is a measurement, and the cash it generated may already be in inventory or equipment. Closing simply moves that measurement into the owner’s stake; Income summary, having done its job, ends at zero.',
  journal:[dr('Income summary',12000,'Income summary held a $12,000 credit (net income). Debiting it for $12,000 brings it to zero.'),cr('Owner capital',12000,'Profit belongs to the owner. Equity grows with a credit — this is how earnings become part of capital.')],
  impact:['Owner capital +$12,000','Income summary $0','Cash unchanged'],
  tally:'Tally carries profit to the Capital / Profit & Loss account automatically on period change; no manual closing voucher is required.', quickbooks:'QuickBooks Online closes net income into Retained earnings automatically at fiscal year-end; set a closing date to lock the year.',
  problem:'A client asks why “Retained earnings” changed even though nobody posted to it.',
  transfer:{question:'Owner drawings of $4,000 also need closing. The entry is:',options:['Debit Owner capital $4,000, credit Owner drawings $4,000','Debit Owner drawings $4,000, credit Cash $4,000','Debit Wages $4,000, credit Owner drawings $4,000'],correct:0,why:'Drawings is a temporary contra-equity account. Closing it reduces Owner capital by the amount withdrawn during the year.'} }
];