import React,{useState} from 'react';
import { Check, Lightbulb, CheckCircle2, XCircle } from 'lucide-react';
export default function DecisionStep({lesson,onSolved,onMistake,solved=false}){
 const [selected,setSelected]=useState(solved?lesson.correct:[]),[result,setResult]=useState(solved?true:null),[deeper,setDeeper]=useState(false);
 const toggle=i=>{if(result===true)return;setSelected(selected.includes(i)?selected.filter(n=>n!==i):[...selected,i]);setResult(null);};
 const check=()=>{const valid=selected.length===lesson.correct.length&&selected.every(n=>lesson.correct.includes(n));setResult(valid);if(valid)onSolved();else onMistake();};
 const reviewed=lesson.options.map((o,i)=>({o,i,chosen:selected.includes(i),right:lesson.correct.includes(i)})).filter(x=>x.chosen||x.right);
 return <div className="space-y-5"><div className="rounded-xl border border-[#e4deee] bg-[#f7f4fb] p-6"><p className="eyebrow mb-3 text-[#a18ebd]">THE REAL-WORLD PROBLEM</p><h2 className="text-xl font-semibold leading-relaxed">{lesson.scenario}</h2></div><p className="text-xs text-[#a29baa]">Select {lesson.correct.length} answers. Think about what the business received, used up, earned, or now owes.</p>
 <div className="grid gap-3 sm:grid-cols-2">{lesson.options.map((option,i)=><button key={i} onClick={()=>toggle(i)} aria-pressed={selected.includes(i)} className={`flex items-center gap-3 rounded-xl border p-4 text-left text-sm ${selected.includes(i)?'border-[#a793d9] bg-[#eee8fb] text-[#7b61ac]':'border-[#e8e5ed] bg-white hover:border-[#c9b9e3]'}`}><span className={`grid h-5 w-5 shrink-0 place-items-center rounded-md border ${selected.includes(i)?'border-[#9780c7] bg-[#9780c7] text-white':'border-[#d8d1e3]'}`}>{selected.includes(i)&&<Check size={13}/>}</span>{option}</button>)}</div>
 {result!==null&&<div role="status" className={`space-y-4 rounded-xl p-5 text-sm leading-relaxed ${result?'bg-[#edf6ef] text-[#4f7a5c]':'bg-[#fff5e7] text-[#8a6a3a]'}`}><h3 className="font-bold">{result?'Exactly. You’re thinking in transactions.':'A useful mistake. Let’s look at each choice.'}</h3>
 <ul className="space-y-2">{reviewed.map(({o,i,chosen,right})=><li key={i} className="flex gap-2 rounded-lg bg-white/70 p-3 text-xs">{right?<CheckCircle2 size={16} className="mt-0.5 shrink-0 text-emerald-600"/>:<XCircle size={16} className="mt-0.5 shrink-0 text-amber-600"/>}<span><b>{o}</b>{chosen&&!right&&<span className="text-amber-700"> — you chose this.</span>}{right&&!chosen&&<span className="text-amber-700"> — you missed this.</span>} {lesson.optionNotes?.[i]}</span></li>)}</ul>
 <p>{lesson.explanation}</p><p className="text-xs"><b>The principle:</b> {lesson.principle}</p>{!result&&lesson.intuition&&<p className="rounded-lg border border-current/20 p-3 text-xs"><b>Why it feels backwards:</b> {lesson.intuition}</p>}</div>}
 <div className="flex flex-wrap items-center gap-4">{result!==true&&<button className="primary-btn" onClick={check} disabled={selected.length!==lesson.correct.length}>Check my thinking</button>}<button onClick={()=>setDeeper(!deeper)} className="flex items-center gap-2 text-xs text-[#9d8ab5]"><Lightbulb size={14}/>{deeper?'Close deeper explanation':'Go deeper'}</button></div>
 {deeper&&<p className="rounded-xl bg-white p-4 text-sm leading-relaxed text-[#8f829e]">{lesson.intuition||lesson.principle} Software can balance a wrong classification automatically — this is why your reasoning matters more than the arithmetic.</p>}</div>;
}