// The terminology bridge. Each entry: [term, aliases, meaning, tally, quickbooks, whatAClientSays, group]
// Aliases are the words an accountant, a Tally user, a QuickBooks user or a business owner
// might use for the same idea. Software notes are conceptual mappings, not click paths.
export const glossaryGroups = ['Core accounting', 'Receivables & payables', 'Period end', 'Canadian tax & payroll', 'Software & migration'];

export const terms = [
 ['Accounts receivable','AR · Trade receivable · Sundry debtor · Customer outstanding balance','A customer owes the business for an invoice already issued.','Sundry Debtors group; bill-wise outstanding under Bills Receivable','Accounts Receivable; open customer invoices and the A/R Ageing Summary','My customer paid, but their balance is still showing.','Receivables & payables'],
 ['Accounts payable','AP · Trade payable · Creditor · Sundry creditor · Vendor outstanding balance','The business owes a supplier for a bill already recorded.','Sundry Creditors group; outstanding bills under Bills Payable','Accounts Payable; unpaid vendor bills','Why does the supplier balance show more than we owe?','Receivables & payables'],
 ['Bill-wise details','Bill allocation · Against reference · Applying a payment','Linking a receipt or payment to the specific invoices it settles, so the ageing clears as well as the balance.','Bill-wise Details on the party ledger; choose Agst Ref rather than On Account','Receive Payment or Pay Bills with the specific invoices ticked; unapplied payments sit as credits','They paid in full, so why is the ageing still showing them overdue?','Receivables & payables'],
 ['Ageing','Aged trial balance · ATB · 30/60/90 · Outstandings','A report splitting what is owed by how overdue it is, measured from the due date.','Outstandings → Receivables / Payables, with ageing by bill date or due date','A/R and A/P Ageing Summary and Detail','How much of this is actually collectible?','Receivables & payables'],
 ['Credit memo','Credit note · Customer credit · Sales return','Reduces an amount owed by a customer, usually for a return or a billing correction.','Credit Note voucher, allocated against the original bill','Credit memo applied to an invoice; a refund is a separate transaction','We returned the goods but the invoice balance is unchanged.','Receivables & payables'],
 ['Vendor credit','Supplier credit · Purchase return · Debit note in the buyer’s books','Reduces what the business owes a supplier. Which note it is called depends on whose books you are reading.','Debit Note voucher for purchase returns and supplier adjustments','Vendor credit applied to a bill','The supplier gave us a credit. Why is the full bill still payable?','Receivables & payables'],
 ['Bad debt & allowance','Provision for doubtful debts · Write-off · Expected credit loss','An estimate of receivables that will not be collected, and the later removal of a specific dead balance.','Bad Debts ledger and a Provision for Doubtful Debts ledger, grouped per policy','Bad debt expense with an allowance contra-A/R account; write-offs use a credit memo','Half of this receivable is two years old. Is it still an asset?','Receivables & payables'],

 ['Journal entry','JE · General journal · Manual entry · Journal voucher','A record of debits and credits describing one accounting event. Most transactions post automatically; a journal is for what does not.','Journal voucher; Sales, Purchase, Receipt, Payment and Contra vouchers also post entries','Journal entry; invoices, bills and expenses post automatically behind the scenes','Can we fix this with a journal, or will that break customer balances?','Core accounting'],
 ['General ledger','GL · Account activity · Ledger vouchers · Transaction history','The detailed postings to each account, with dates and a running balance.','Display → Account Books → Ledger','General Ledger report; the account register','Which transaction changed this balance?','Core accounting'],
 ['Chart of accounts','COA · Ledgers and groups · Account list','The full list of accounts, organised so each one reports in the right place.','Ledgers sit under Groups (Sundry Debtors, Indirect Expenses, Capital Account). The group decides the statement line.','Accounts with a Type and Detail Type; the type decides the statement line','Do we need a new account for this, or does one already cover it?','Core accounting'],
 ['Trial balance','TB · Debit and credit balances · Working trial balance','A list of ledger balances checking that total debits equal total credits. Balanced does not mean error-free.','Trial Balance report, drillable to the vouchers behind each balance','Trial Balance report','Everything balances, so why is the profit still wrong?','Core accounting'],
 ['Revenue','Sales · Income · Turnover · Top line','Value earned by delivering goods or services — not every bank deposit.','Sales Accounts and other income ledgers under Direct/Indirect Income','Income accounts and the sales items mapped to them','Why is income higher than the money in my bank?','Core accounting'],
 ['Cost of goods sold','COGS · Cost of sales · Direct costs','The cost of the specific goods or services sold, matched to the revenue they produced.','Derived from stock item valuation, or posted through purchase and consumption ledgers','The COGS account mapped on each inventory item','Our margin looks like 100%. Where is the cost?','Core accounting'],
 ['Gross vs net','Gross profit · Net income · Bottom line · Margin','Gross profit is revenue less direct costs. Net income is what remains after every other cost.','Profit & Loss shows Gross Profit then Nett Profit','Profit and Loss report with a Gross Profit subtotal','We have good margins but no profit. How?','Core accounting'],
 ['Accrual vs cash basis','Accruals basis · Cash accounting · Reporting basis','Accrual records revenue when earned and costs when incurred. Cash records both when money moves.','Vouchers post on the accrual basis; Receipts and Payments gives the cash view','Reports have an Accounting Method toggle: Cash or Accrual','You said we made $12,000 but the bank went down.','Core accounting'],
 ['Capitalise vs expense','Capex vs opex · Fixed asset vs running cost','A cost with lasting future benefit becomes an asset; a cost consumed now becomes an expense.','Fixed Assets group versus Indirect Expenses','A Fixed Asset account type versus an Expense account','Why did buying the laptop not reduce my profit?','Core accounting'],
 ['Contra account','Offset account · Provision · Accumulated depreciation · Allowance','An account that sits against another and reduces it, while leaving the original figure visible. In Tally, a Contra *voucher* means something unrelated: a cash-to-bank transfer.','Contra voucher (F4) = cash ↔ bank. Provisions and accumulated depreciation are separate ledgers.','Accumulated depreciation and allowance accounts sit under the asset they reduce','Why is there a negative number inside our assets?','Core accounting'],
 ['Equity','Owner capital · Share capital · Retained earnings · Net assets','The residual claim on assets after liabilities. Contributions, withdrawals and accumulated profit are different components.','Capital Account group, with Reserves & Surplus','Equity accounts; retained earnings and current-year net income','Why did my personal investment show up as business income?','Core accounting'],
 ['Shareholder loan','Due to shareholder · Director’s loan · Loan from shareholder','Money the corporation owes its owner, or the owner owes the corporation. A corporation has no “drawings”.','A ledger under Unsecured Loans or Loans (Liability) — not under Capital Account','A “Due to shareholder” liability account','I paid company bills on my personal card. Where does that go?','Core accounting'],

 ['Adjusting entry','AJE · Year-end adjustment · Period-end journal','A journal that moves revenue or cost into the period it belongs to: accruals, prepayments, depreciation, cut-off.','Journal voucher dated in the closing period','Journal entry dated at period end, often set up as recurring','Why did the accountant change last year’s profit?','Period end'],
 ['Accrual (accrued expense)','Accrued liability · Outstanding expense · Provision for expenses','A cost incurred but not yet invoiced or paid, recorded so the period carries its true cost.','Outstanding expense ledger under Current Liabilities','An accrued liabilities account cleared when the bill or payment lands','Nothing was paid. Why is there an expense?','Period end'],
 ['Prepayment','Prepaid expense · Deferred charge · Expense paid in advance','A payment for future benefit. It is an asset until the benefit is used up.','A Prepaid Expenses ledger under Current Assets, released monthly by journal','An Other Current Asset account, released by a recurring journal entry','Why is January a disaster every year?','Period end'],
 ['Deferred revenue','Unearned revenue · Advance from customer · Customer deposit','Cash received before delivery. It is a liability until the promise is fulfilled.','Advance from Customers ledger under Current Liabilities','An Unearned Revenue liability account, recognised as the work is delivered','They paid for the year upfront, so why is it not all income?','Period end'],
 ['Unbilled revenue','Accrued revenue · Work in progress · WIP','Work performed but not yet invoiced. An asset, and the mirror image of deferred revenue.','Accrued Income ledger under Current Assets, reversed when the sales voucher is raised','An Unbilled Revenue other-current-asset account, reversed on invoicing','We did the work in December. Why does December look empty?','Period end'],
 ['Cut-off','Period cut-off · Date accuracy · Which year does this belong to','Deciding the period a transaction belongs to, based on when value moved — not when paperwork arrived.','Period restrictions and security control on back-dated vouchers','A password-protected Closing Date','This invoice is dated January but it is for December work.','Period end'],
 ['Depreciation','Amortisation · Writing down · Book depreciation','Spreading an asset’s cost over its useful life. An estimate, not a cash movement.','Journal voucher to Depreciation and Accumulated Depreciation; Tally does not calculate it','A recurring journal entry; QuickBooks does not calculate it','The machine is three years old and still shows full cost.','Period end'],
 ['Closing the books','Year-end close · Roll-forward · Retained earnings transfer','Emptying revenue, expense and drawings accounts into equity so the new period starts at zero.','Profit is carried to the Profit & Loss / Capital account automatically on period change','Net income closes to Retained Earnings automatically at fiscal year-end','Retained earnings changed and nobody posted to it.','Period end'],
 ['Working papers','Lead schedules · Year-end file · Supporting schedules','The accountant’s schedules supporting each balance: bank, receivables, inventory, accruals, fixed assets.','Exported reports plus external schedules; Tally holds the ledgers, not the file','Exported reports plus the accountant’s own workpapers','What do you need from me for year-end?','Period end'],

 ['GST/HST','Sales tax · Output tax · Tax collected','Tax charged on taxable supplies and held on behalf of the CRA. It is a liability, never revenue.','Use the Canadian tax setup. India’s CGST/SGST/IGST is a different system with different returns.','Sales tax codes by province; the Sales Tax centre tracks what is owed','That $130 is part of my sales, isn’t it?','Canadian tax & payroll'],
 ['Input tax credit','ITC · Recoverable tax · Tax paid on purchases','GST/HST paid on eligible commercial purchases, recoverable by a registrant against tax collected.','A recoverable input tax ledger; do not post purchases tax-inclusive','Purchase tax codes feed the ITC line of the return','Why does the tax we pay on purchases not reduce what we owe?','Canadian tax & payroll'],
 ['Net tax / remittance','Filing position · Amount owing · Refund position','Tax collected less input tax credits. Only the difference is paid — or refunded if credits are larger.','A journal clearing the output and input tax ledgers against the bank','Prepare return posts the net payable to the Receiver General','Do we send them everything we charged?','Canadian tax & payroll'],
 ['Source deductions','Withholdings · Statutory deductions · CPP, EI and income tax','Amounts held back from an employee’s pay and owed to the CRA until remitted.','Pay heads split earnings, employee deductions and employer contributions','A payroll run posts wages, deductions and the payroll liability','Gross is $2,000 but they only got $1,550.','Canadian tax & payroll'],
 ['Employer contributions','Employer portion · Fully loaded cost · Employer CPP and EI','The employer’s own share on top of gross pay. CPP is matched dollar for dollar; employer EI is a higher multiple than the employee’s. Rates and ceilings change annually.','Employer contribution pay heads, configured for the country of the books','A separate employer taxes expense posted by the payroll run','We budgeted salaries and came in over. Nobody got a raise.','Canadian tax & payroll'],
 ['Payroll remittance','PD7A · Source deduction remittance · Paying the CRA','Sending the CRA the employee withholdings plus the employer share. It settles a liability; it is not a new expense.','Payment voucher clearing the statutory liability ledgers','A payroll liability payment, not an expense','We pay them every month but the liability keeps growing.','Canadian tax & payroll'],
 ['Capital cost allowance','CCA · Tax depreciation · Class pools','The tax deduction for capital assets. Declining balance, computed on class pools — never a ledger posting, and separate from book depreciation.','Not calculated by Tally; the schedule lives in the tax file','Not calculated by QuickBooks; the tax preparer maintains the pools','Depreciation is $9,000 in the books and $14,000 on the return.','Canadian tax & payroll'],
 ['Dividend vs salary','Owner compensation · T4 vs T5 · Remuneration mix','The three ways money leaves a corporation for its owner: salary, dividend, or repayment of a shareholder loan. Each is reported differently.','Separate ledgers for salary, dividends declared, and the shareholder loan','Payroll for salary; an equity account for dividends; a liability for the loan','Can I just take money out of the company?','Canadian tax & payroll'],

 ['Bank reconciliation','Bank rec · Clearing · Matching the bank','Explaining every difference between the bank statement and the ledger. Separate from processing a bank feed.','Banking → Bank Reconciliation, using bank/clearing dates','Reconcile — a distinct process from the Banking feed','The software balance does not match the statement.','Software & migration'],
 ['Bank feed: match vs add','Categorising · For review · Bank rules','Add creates a new record. Match links a feed line to a record that already exists. Choosing wrong either duplicates or omits.','No live feed; import or reconcile the statement and post the missing vouchers','Banking → For Review; rules pre-fill the category but still only propose an Add','I finished the bank feed, so the books are done — right?','Software & migration'],
 ['Items','Products and services · Stock items · Item mapping','What the business sells, mapped to the accounts that record it. The item, not the invoice, decides the accounts.','Stock items with units, valuation method and godowns','Products and Services, each mapped to income, inventory and COGS accounts','Every sale shows 100% margin.','Software & migration'],
 ['Inventory valuation','Costing method · FIFO · Weighted average','The rule deciding which cost leaves as COGS and which stays in stock. Total cost is fixed; only the split changes.','Valuation method set per stock item (FIFO, Avg Cost and others)','QuickBooks Online uses FIFO for inventory items','Two branches, same product, different margins.','Software & migration'],
 ['Cost centres / classes','Dimensions · Departments · Locations · Projects · Tracking categories','A second dimension on a transaction, so one chart of accounts can report by store, department or job.','Cost Centres and Cost Categories, allocated on the voucher','Classes, Locations and Projects (plan-dependent)','I want profit per store. Do I need a second company file?','Software & migration'],
 ['Opening balances','Conversion balances · Migration · Go-live balances','The balance sheet carried into new software as at the day before go-live. Not revenue, and not new transactions.','Set on each ledger under Accounts Info; unbalanced amounts land in Difference in Opening Balances','Opening Balance Equity is populated automatically and must be cleared once verified','We switched software and suddenly reported a year of sales in one day.','Software & migration'],
 ['Audit trail','Change log · Alteration history · Void vs delete','The record of who changed what and when. Correcting is safer than deleting — a deletion hides the history too.','Alteration and deletion tracking under security control and Tally Audit','The Audit Log; void keeps the record, delete removes it','Can we just delete the wrong one?','Software & migration'],
 ['Suspense','Difference in opening balances · Uncategorised · Ask my accountant','A holding account for what is not yet understood. Useful briefly, dangerous permanently.','Suspense A/c and Difference in Opening Balances','Uncategorised Asset / Income / Expense and Opening Balance Equity','What is this “Uncategorised” balance on our books?','Software & migration']
];
