import React,{useState} from 'react';
import { HelpCircle, CheckCircle2 } from 'lucide-react';
import { money } from '@/components/accounting/accountingData';
import JournalFeedback from '@/components/accounting/JournalFeedback';
export default function JournalBuilder({lesson,onSolved,onMistake,solved=false}){
 const answer=()=>Object.fromEntries(lesson.journal.map((l,i)=>[i,l.debit?'debit':'credit']));
 const [sides,setSides]=useState(()=>solved?answer():{}),[feedback,setFeedback]=useState(solved?true:null),[checked,setChecked]=useState(()=>solved?answer():null),[why,setWhy]=useState(false);
 const total=side=>lesson.journal.reduce((sum,l,i)=>sum+(sides[i]===side?l.debit+l.credit:0),0);
 const check=()=>{const valid=lesson.journal.every((l,i)=>sides[i]===(l.debit?'debit':'credit'));setChecked({...sides});setFeedback(valid);if(valid)onSolved();else onMistake();};
 return <div className="space-y-5"><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold">Build the entry underneath.</h2><p className="muted mt-2">Place each amount on the side of its T-account that matches what actually happened.</p></div><button onClick={()=>setWhy(!why)} className="secondary-btn"><HelpCircle size={15}/>Why?</button></div>
 {why&&<div className="rounded-xl bg-[#f3f0fc] p-4 text-sm leading-relaxed text-[#837099]"><p><b>Debit and credit are not “money out” and “money in”.</b> Your bank statement uses those words from the bank’s point of view — your deposit is money the bank owes you, so the bank credits it. In your own books the logic is different: assets and expenses grow on the debit side; liabilities, equity, and revenue grow on the credit side.</p><p className="mt-2">Ask two questions for each account: <i>what did the business receive, use up, earn, or now owe?</i> — and <i>did that account go up or down?</i></p><p className="mt-2">{lesson.principle}</p></div>}
 <div className="grid gap-4 sm:grid-cols-2">{lesson.journal.map((l,i)=><div key={l.account} className="panel p-4"><h3 className="border-b-2 border-[#cfc8e6] pb-3 text-center text-sm font-semibold">{l.account}</h3><div className="grid grid-cols-2 divide-x divide-[#dcd7ec]">{['debit','credit'].map(side=><button key={side} disabled={feedback===true} onClick={()=>{setSides({...sides,[i]:side});setFeedback(null);}} className={`py-5 text-center text-xs ${sides[i]===side?'bg-[#efebfb] text-[#785cc9]':'text-[#a19bab] hover:bg-[#f8f6fc]'}`}><span className="block capitalize">{side}</span><strong className="mt-3 block text-base">{sides[i]===side?money(l.debit+l.credit):'+'}</strong></button>)}</div></div>)}</div>
 <div className="flex flex-wrap justify-between gap-3 text-sm"><span>Debits: <b>{money(total('debit'))}</b></span><span>Credits: <b>{money(total('credit'))}</b></span></div>
 {feedback!==null&&checked&&<JournalFeedback lesson={lesson} sides={checked} correct={feedback}/>}
 {feedback===true?<p className="flex items-center gap-2 text-sm text-emerald-600"><CheckCircle2 size={18}/>That’s the accounting engine at work.</p>:<button onClick={check} disabled={Object.keys(sides).length!==lesson.journal.length} className="primary-btn">Check my journal</button>}</div>;
}