import React, {useState} from 'react';
import { Outlet, Link } from 'react-router-dom';
import { Menu, Flame, ChevronDown, LogOut, Zap } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import { useLearning } from '@/components/accounting/LearningProvider';
import Sidebar from '@/components/accounting/Sidebar';
export default function LayoutContent(){
 const [open,setOpen]=useState(false),[profile,setProfile]=useState(false); const {user,streak}=useLearning();
 return <div className="min-h-screen"><Sidebar open={open} onClose={()=>setOpen(false)}/><div className="lg:ml-[238px]"><header className="flex h-[76px] items-center justify-between border-b border-[#e9eaf1] bg-white/70 px-5 md:px-9"><div className="flex items-center gap-3"><button onClick={()=>setOpen(true)} className="lg:hidden" aria-label="Open navigation"><Menu size={21}/></button><span className="hidden text-[11px] text-[#a4a5b3] sm:block">Your next <span className="text-[#86809b]">aha! moment</span> is one problem away.</span></div><div className="flex items-center gap-5"><Link to="/learn?mode=daily" className="flex items-center gap-1.5 text-[11px] text-[#aaa1bf]"><Zap size={14} className="text-[#b2a2d3]"/><span className="hidden sm:inline">10 minutes for you</span></Link><span className="flex items-center gap-1.5 border-l border-[#e9e8ef] pl-5 text-xs font-semibold text-[#c49b65]"><Flame size={17}/>{streak}<span className="hidden font-normal text-[#a3a0aa] sm:inline">day streak</span></span><div className="relative"><button onClick={()=>setProfile(!profile)} className="flex items-center gap-2" aria-label="Account menu" aria-expanded={profile}><span className="grid h-8 w-8 place-items-center rounded-full bg-[#e9e2f2] text-xs font-bold text-[#9680ac]">{(user?.full_name||user?.email||'L').slice(0,1).toUpperCase()}</span><ChevronDown size={12} className="text-[#a6a3b1]"/></button>{profile&&<div className="absolute right-0 top-11 z-20 w-52 rounded-xl border bg-white p-3 shadow-lg"><p className="mb-3 truncate text-xs text-[#8f8a9b]">{user?.email}</p><button onClick={()=>base44.auth.logout('/login')} className="flex items-center gap-2 text-sm"><LogOut size={14}/> Sign out</button></div>}</div></div></header><main className="mx-auto max-w-[1450px] px-5 py-8 md:px-9"><Outlet/></main><footer className="mx-auto flex max-w-[1450px] flex-wrap justify-between gap-2 px-5 pb-5 text-[9px] text-[#b2b3c0] md:px-9"><span>Built for real business. Designed for your brain.</span><span>Learning simulations only · Not accounting or tax advice</span></footer></div></div>;
}