import { advancedLessons } from '@/components/accounting/advancedLessons';
import { appliedLessons } from '@/components/accounting/appliedLessons';
export const dr = (account, amount, why) => ({ account, debit: amount, credit: 0, why });
export const cr = (account, amount, why) => ({ account, debit: 0, credit: amount, why });
const core = [
 { id:'equipment', level:'Beginner', short:'Credit purchase', title:'A purchase. Two changes.', topic:'Transaction Logic',
  scenario:'Maple Coffee buys a $2,000 laptop on credit. No money leaves the bank today. Which TWO accounts increase?',
  options:['Cash','Accounts payable','Equipment','Revenue','Rent expense','Owner capital'], correct:[1,2],
  optionNotes:['Cash: untouched — the laptop is on credit, so no money leaves today.','Accounts payable: up — the supplier is owed $2,000 until Maple pays.','Equipment: up — Maple now owns a laptop it will use for years.','Revenue: unchanged — buying something never earns anything.','Rent expense: unchanged — a laptop is a lasting asset, not a cost used up this month.','Owner capital: unchanged — the owner put nothing in; the supplier financed this.'],
  explanation:'Maple received a laptop it owns (Equipment up) and now owes the supplier for it (Accounts payable up). Cash and profit do not move — nothing was paid and nothing was used up.',
  principle:'Every transaction keeps Assets = Liabilities + Equity. An asset can be funded by a liability, not just by cash.',
  intuition:'Most people want to credit Equipment — Maple “got” something, and getting feels like a credit. That is your bank statement talking: when the bank credits you, it is recording what it owes you. In Maple’s own books everything Maple owns lives on the debit side, so a new laptop is a debit to Equipment. The credit goes to the supplier Maple now owes.',
  journal:[dr('Equipment',2000,'Maple now owns a $2,000 laptop. Assets grow on the debit side.'),cr('Accounts payable',2000,'The supplier has not been paid. Maple owes $2,000, and a new debt is a credit — the mirror image of the asset received.')],
  impact:['Assets +$2,000','Liabilities +$2,000','Profit unchanged'],
  tally:'Purchase voucher → fixed asset ledger and supplier ledger; bill-wise allocation tracks the amount owed.', quickbooks:'Bill → categorize to Equipment, not an expense. The bill creates a payable. Payment happens later.',
  problem:'A customer says profit fell after buying a laptop. Check whether it was expensed instead of capitalized.',
  transfer:{question:'An espresso machine costs $4,000, payable next month. What happens today?',options:['Cash falls $4,000','Equipment and payables rise $4,000','Revenue rises $4,000'],correct:1,why:'Maple received the machine today, so the asset exists today. Payment terms delay the cash, not the asset or the debt.'} },
 { id:'capital', level:'Beginner', short:'Owner investment', title:'Your first $20,000', topic:'Transaction Logic',
  scenario:'You transfer $20,000 of personal savings into Maple Coffee’s bank account. Which TWO accounts increase?',
  options:['Cash','Revenue','Owner capital','Loan payable'], correct:[0,2],
  optionNotes:['Cash: up — $20,000 landed in the business bank account.','Revenue: unchanged — nothing was sold; this is funding, not earnings.','Owner capital: up — your claim on the business grew by $20,000.','Loan payable: unchanged — nobody has to be repaid; this is ownership, not borrowing.'],
  explanation:'Cash rises because money arrived. But it came from you, not from a customer, so it is not revenue — it is your stake in the business, recorded as Owner capital.',
  principle:'Owner contributions increase equity directly. They never pass through profit.',
  intuition:'Money arrived, so it is tempting to call it income — “money in” feels like revenue. But revenue is earned by delivering something to customers. This is the owner funding the business, so the business now owes its owner a bigger stake. Cash is debited (asset up); Owner capital is credited (equity up).',
  journal:[dr('Cash',20000,'Money arrived in the business account — an asset growing, debit.'),cr('Owner capital',20000,'This is the owner’s stake, not a customer sale. Equity grows with a credit.')],
  impact:['Cash +$20,000','Equity +$20,000','Revenue unchanged'],
  tally:'Receipt voucher → bank and capital ledgers.', quickbooks:'Bank deposit categorized to the owner equity account.',
  problem:'A bank-feed deposit was categorized as sales, overstating revenue.',
  transfer:{question:'A bank lends Maple Coffee $10,000. Which account offsets the cash increase?',options:['Revenue','Owner capital','Loan payable'],correct:2,why:'The bank must be repaid, so the other side is a debt. No sale happened and the owner contributed nothing.'} },
 { id:'invoice', level:'Beginner', short:'Credit sale', title:'You made a sale. Where is the cash?', topic:'AR/AP',
  scenario:'Cedar Studio buys $1,000 of catering services, payable in 30 days. The work is complete. Which TWO accounts increase?',
  options:['Cash','Accounts receivable','Revenue','Accounts payable'], correct:[1,2],
  optionNotes:['Cash: unchanged — Cedar has 30 days; nothing arrived today.','Accounts receivable: up — Cedar owes $1,000; a customer’s promise to pay is an asset.','Revenue: up — the catering was delivered, so the income is earned now.','Accounts payable: unchanged — that is what Maple owes others, not what customers owe Maple.'],
  explanation:'The work is done, so the revenue is earned today. Maple does not have cash yet — it has Cedar’s promise to pay, which is an asset called Accounts receivable.',
  principle:'Under accrual accounting, earning revenue and collecting cash are two separate events.',
  intuition:'The instinct is that a sale is not real until the money shows up. Accrual accounting disagrees: the service has been delivered, so Maple has earned it. What Maple lacks is cash — instead it holds a right to collect $1,000, and a right to collect is an asset, debited like any other asset.',
  journal:[dr('Accounts receivable',1000,'Cedar Studio owes Maple $1,000. A right to collect money is an asset — debit.'),cr('Revenue',1000,'The work is complete, so the income is earned today. Revenue is credited even though no cash arrived.')],
  impact:['Receivables +$1,000','Profit +$1,000','Cash unchanged'],
  tally:'Sales voucher → customer (sundry debtor) and sales ledgers.', quickbooks:'Invoice → customer balance increases and service revenue is recognized.',
  problem:'The business reports profit but cannot pay rent: its sales may still be sitting in receivables.',
  transfer:{question:'Another $800 service invoice is issued with nothing collected. How much operating cash arrived?',options:['$800','$0','$1,000'],correct:1,why:'An invoice creates a claim to cash. Cash arrives only when the customer pays.'} },
 { id:'collection', level:'Beginner', short:'Customer receipt', title:'Paid does not mean sold again', topic:'AR/AP',
  scenario:'Cedar Studio pays a previously recorded $1,000 invoice. Which TWO accounts change?',
  options:['Cash increases','Revenue increases','Accounts receivable decreases','Accounts payable decreases'], correct:[0,2],
  optionNotes:['Cash increases: yes — $1,000 arrived in the bank.','Revenue increases: no — the revenue was recorded when the invoice was issued.','Accounts receivable decreases: yes — Cedar no longer owes the $1,000.','Accounts payable decreases: no — this is a customer paying Maple, not Maple paying a supplier.'],
  explanation:'Cash replaces the receivable. The sale was already counted on invoice day; recording revenue again would count the same $1,000 twice.',
  principle:'Settling a receivable swaps one asset for another. It is not new income.',
  intuition:'Cash arriving from a customer feels like a sale — but the sale happened when the invoice went out. Today Maple simply converts a promise (receivable) into money (cash). Both are assets: one goes up with a debit, the other down with a credit, and profit does not move.',
  journal:[dr('Cash',1000,'Money arrived — asset up, debit.'),cr('Accounts receivable',1000,'Cedar’s debt to Maple is settled, so the receivable shrinks — credit. Nothing is earned here; it was earned on invoice day.')],
  impact:['Cash +$1,000','Receivables −$1,000','Profit unchanged'],
  tally:'Receipt voucher → allocate against the original bill reference.', quickbooks:'Receive payment → select the open invoice. Match the bank-feed receipt to it instead of adding new sales income.',
  problem:'The customer paid but the invoice shows unpaid: inspect the payment’s customer and invoice allocation.',
  transfer:{question:'A $450 bank receipt was added as sales although the invoice already exists. What should you investigate?',options:['Whether sales were counted twice','Whether rent is too high','Whether payroll was remitted'],correct:0,why:'The receipt likely duplicates the invoice’s revenue. Reclassify it as a payment against the invoice.'} },
 { id:'rent', level:'Beginner', short:'Rent payment', title:'Not every payment buys an asset', topic:'Financial Statements',
  scenario:'Pay $2,000 for rent used this month. Which TWO changes happen?',
  options:['Cash decreases','Equipment increases','Rent expense increases','Revenue decreases'], correct:[0,2],
  optionNotes:['Cash decreases: yes — $2,000 left the bank.','Equipment increases: no — renting space gives Maple no lasting asset.','Rent expense increases: yes — a month of space was used up.','Revenue decreases: no — costs reduce profit through expenses, never by lowering revenue.'],
  explanation:'This month’s space has been consumed and nothing lasting is left. A cost with no future benefit is an expense; cash falls to pay for it.',
  principle:'Consumed benefits are expenses. Future benefits are assets (prepaid rent would be one).',
  intuition:'Debits feel like they should be reserved for things you own — so why is an expense debited? Because expenses and assets are both things the business paid for. The difference is that an asset still has future value, while an expense is used up. Both sit on the debit side; Cash, the asset given up, is credited.',
  journal:[dr('Rent',2000,'A month of space was consumed with nothing left to show — an expense, debited.'),cr('Cash',2000,'Cash left the account — asset down, credit.')],
  impact:['Cash −$2,000','Expenses +$2,000','Profit −$2,000'],
  tally:'Payment voucher → rent expense and bank ledgers.', quickbooks:'Expense → rent category and the paying bank account. If a bill exists, pay that bill instead.',
  problem:'Entering an expense and also paying an existing bill duplicates the rent cost.',
  transfer:{question:'You pay a rent bill already entered last week. Which balance decreases alongside cash?',options:['Revenue','Accounts payable','Equipment'],correct:1,why:'The expense was recognized when the bill was entered. Paying it now settles the payable — don’t expense it twice.'} },
 { id:'bank', level:'Beginner', short:'Bank fee', title:'The case of the missing $35', topic:'Bank Reconciliation',
  scenario:'The bank shows a $35 fee missing from your ledger. Which TWO changes bring the books up to date?',
  options:['Bank fees increase','Cash decreases','Revenue increases','Loan payable increases'], correct:[0,1],
  optionNotes:['Bank fees increase: yes — the bank charged Maple for a service.','Cash decreases: yes — the fee already left the account.','Revenue increases: no — the bank charged Maple; Maple earned nothing.','Loan payable increases: no — Maple did not borrow anything.'],
  explanation:'The fee is a real cost Maple never recorded. Record the expense and bring book cash down by $35 so it matches the bank.',
  principle:'Reconciliation separates timing differences from entries that are genuinely missing or wrong.',
  intuition:'When the bank balance is lower than the books, the temptation is to plug the difference so the numbers agree. But this is not a timing gap — the bank really took $35. It gets the same shape as any payment (expense debited, Cash credited); you are just recording it late.',
  journal:[dr('Bank fees',35,'A service the bank charged for — cost used up, expense debited.'),cr('Cash',35,'The money already left the account; book cash must come down — credit.')],
  impact:['Cash −$35','Expenses +$35','Profit −$35'],
  tally:'Payment voucher → bank charges ledger; then reconcile the bank entry.', quickbooks:'Add the bank fee once from the feed, then match and reconcile.',
  problem:'The bank is $35 below the books. Check for unrecorded fees before creating a balancing adjustment.',
  transfer:{question:'A $500 cheque is in your books but has not cleared the bank. Should you record the expense again?',options:['Yes, reduce cash again','No, mark it as an outstanding cheque','Delete the original cheque'],correct:1,why:'This one is a timing difference. The book entry is right; the bank just hasn’t caught up.'} },
 { id:'inventory', level:'Beginner', short:'Cost of sales', title:'The second half of a sale', topic:'Inventory',
  scenario:'Maple sells coffee bags for $500. Those bags cost $200. Revenue is already recorded. Which TWO cost-side changes are still needed?',
  options:['Inventory decreases $200','Cost of goods sold increases $200','Cash decreases $200','Revenue decreases $200'], correct:[0,1],
  optionNotes:['Inventory decreases $200: yes — bags that cost $200 are gone from the shelf.','Cost of goods sold increases $200: yes — that cost is now used up.','Cash decreases $200: no — the cost side of a sale never touches cash.','Revenue decreases $200: no — cost never reduces revenue; it reduces profit as an expense.'],
  explanation:'The bags had a cost, and that cost has to leave the asset column when they leave the shelf. Inventory falls; Cost of goods sold rises. Gross profit is $500 − $200 = $300.',
  principle:'Match the cost of goods sold with the revenue they produced, in the same period.',
  intuition:'Most people record the sale and stop — the customer paid, done. But the $200 of coffee that walked out the door was an asset a minute ago. If you don’t move it to expense, inventory stays overstated and profit looks like $500 instead of $300. No cash moves in this half of the sale.',
  journal:[dr('Cost of goods sold',200,'The $200 the bags cost is now used up — an expense, debited.'),cr('Inventory',200,'The bags are gone from the shelf — asset down, credit.')],
  impact:['Inventory −$200','COGS +$200','Gross profit $300 on the $500 sale'],
  tally:'Stock-item sales affect quantity and valuation; COGS treatment depends on inventory configuration.', quickbooks:'A sale of an inventory item records revenue and, with tracking on, posts inventory and COGS automatically.',
  problem:'Inventory went negative: inspect missing purchase receipts, wrong items, dates, and quantities before adjusting.',
  transfer:{question:'Sell goods for $900 that cost $350. What is gross profit before other costs?',options:['$900','$550','$350'],correct:1,why:'Gross profit is sales minus the cost of the goods sold: $900 − $350 = $550.'} },
 { id:'tax', level:'Beginner', short:'HST sale', title:'That $130 is not your revenue', topic:'GST/HST',
  scenario:'A taxable Ontario service is sold for $1,000 plus 13% HST and paid immediately. Besides Cash, which TWO accounts increase?',
  options:['Revenue by $1,000','Revenue by $1,130','HST payable by $130','Wages by $130'], correct:[0,2],
  optionNotes:['Revenue by $1,000: yes — that is the price Maple earned for the service.','Revenue by $1,130: no — the extra $130 belongs to the government, not Maple.','HST payable by $130: yes — Maple holds tax it owes the CRA; a liability.','Wages by $130: no — tax collected has nothing to do with staff pay.'],
  explanation:'Maple earned $1,000 and collected $130 on behalf of the tax authority. Total cash in is $1,130, but only $1,000 of it is revenue.',
  principle:'Sales tax collected is a liability, not revenue. (Assumes an Ontario registrant and a fully taxable supply.)',
  intuition:'The customer handed over $1,130, so it feels like $1,130 of sales. But $130 of it was never Maple’s to keep — it must be passed to the CRA. Holding someone else’s money is a debt, which is why part of a cash sale ends up as a liability.',
  journal:[dr('Cash',1130,'The full $1,130 landed in the bank — asset up, debit.'),cr('Revenue',1000,'Maple earned only $1,000 of it — credit revenue for that.'),cr('HST payable',130,'The $130 belongs to the CRA. Holding someone else’s money is a liability — credit.')],
  impact:['Cash +$1,130','Revenue +$1,000','Tax liability +$130'],
  tally:'Use jurisdiction-appropriate tax ledgers. Indian GST (CGST/SGST/IGST) is not Canadian HST.', quickbooks:'Apply the Canadian sales tax code. Verify place of supply, registration, taxability, and inclusive/exclusive settings.',
  problem:'An invoice’s tax looks wrong: inspect tax code, customer location, line taxability, and whether the price includes tax.',
  transfer:{question:'A $113 price includes 13% HST. What is the tax portion?',options:['$14.69','$13','$0'],correct:1,why:'Divide $113 by 1.13 to get the $100 base. The remaining $13 is HST — not 13% of the tax-inclusive total.'} },
 { id:'payroll', level:'Beginner', short:'Payroll run', title:'Why gross pay is not the deposit', topic:'Payroll',
  scenario:'Gross wages are $1,500, with $300 employee deductions and $1,200 net cash paid. Besides Cash, which TWO accounts change?',
  options:['Wages increase $1,500','Wages increase $1,200','Payroll payable increases $300','Revenue increases $300'], correct:[0,2],
  optionNotes:['Wages increase $1,500: yes — that is what staff earned and what Maple owes in total.','Wages increase $1,200: no — that is the net deposit, not the full cost of labour.','Payroll payable increases $300: yes — withheld amounts are owed to the CRA until remitted.','Revenue increases $300: no — withholding tax earns Maple nothing.'],
  explanation:'The full $1,500 is the cost of labour. Only $1,200 went to employees; the $300 withheld is owed to the authorities until Maple remits it.',
  principle:'Employee deductions create liabilities until remitted. (Employer contributions are additional expense, omitted here.)',
  intuition:'Seeing $1,200 leave the bank, people record $1,200 of wages. But the employees earned $1,500 — Maple is just holding back $300 to pay the CRA on their behalf. The expense is the whole $1,500; the unpaid $300 is a debt, not a saving.',
  journal:[dr('Wages',1500,'The full $1,500 of labour was consumed — expense debited.'),cr('Cash',1200,'Only the $1,200 net pay left the bank — credit that amount.'),cr('Payroll payable',300,'The $300 withheld is owed to the CRA — a liability, credited.')],
  impact:['Cash −$1,200','Wages +$1,500','Liabilities +$300'],
  tally:'Payroll vouchers allocate pay heads and statutory liabilities using the country setup.', quickbooks:'A payroll run posts wages, net pay, and payroll liabilities. Remittances settle the liabilities.',
  problem:'Payroll liability stays high after remittance: check that the payment hit the liability account.',
  transfer:{question:'The withheld $300 is remitted. What is the debit?',options:['Wages expense','Payroll payable','Revenue'],correct:1,why:'Remittance clears the existing liability. The wages cost was already recorded on payday.'} }
];
export const lessons = [...core, ...advancedLessons, ...appliedLessons];
export const getLesson = id => lessons.find(l => l.id === id) || lessons[0];