import React from 'react';
import { Link } from 'react-router-dom';
import { Coffee, Headphones, ArrowUpRight, ArrowRight, Sprout } from 'lucide-react';
import { useLearning } from '@/components/accounting/LearningProvider';
import { money,summarize } from '@/components/accounting/accountingData';
import { supportCases } from '@/components/accounting/supportData';
export default function PracticeCards(){
 const {transactions}=useLearning(); const day=transactions.at(-1)?.day||0, {balances}=summarize(transactions);
 return <section><div className="mb-4 flex items-center justify-between"><h2 className="text-base font-bold">Less theory. More real life.</h2><span className="text-[10px] text-[#999bab]">Your practice playground</span></div><div className="grid gap-4 sm:grid-cols-2"><Link to="/business" className="panel group overflow-hidden hover:border-[#b9d1c4]"><div className="relative flex h-28 items-center justify-center overflow-hidden bg-[#edf3ed]"><div className="absolute bottom-0 h-8 w-full bg-[#e1ebe1]"/><div className="relative flex items-end gap-6"><Sprout className="text-[#9cba99]" size={38}/><div className="relative w-24 rounded-t-lg border-[5px] border-[#e5dac6] bg-[#fdfaf3] pb-3 pt-6 text-center"><div className="absolute -left-3 -right-3 top-0 h-5 rounded-sm bg-[repeating-linear-gradient(90deg,#769788_0px,#769788_12px,#f5eedc_12px,#f5eedc_24px)]"/><Coffee className="mx-auto text-[#6e9380]" size={27}/><span className="text-[7px] font-bold tracking-widest text-[#6e9380]">MAPLE COFFEE</span></div><div className="mb-3 h-9 w-7 rounded-t-full border-4 border-[#cadbc7]"/></div><span className="absolute left-3 top-3 rounded bg-white/75 px-2 py-1 text-[8px] font-semibold text-[#71917d]">BUSINESS SIMULATOR</span></div><div className="p-4"><div className="flex items-center justify-between"><h3 className="text-sm font-bold">Your business. Your books.</h3><ArrowUpRight size={16} className="text-[#9cae9f]"/></div><p className="mt-2 text-[11px] leading-relaxed text-[#9295a4]">Run Maple Coffee Co. One transaction,<br className="hidden xl:block"/> one accounting aha! at a time.</p><div className="mt-4 flex justify-between border-t border-[#eef0ef] pt-3 text-[10px]"><span className="text-[#81998a]">Day {day} of 90</span><span className="text-[#999eaa]">Cash: {money(balances.Cash)}</span></div></div></Link>
 <Link to="/support" className="panel group overflow-hidden hover:border-[#d4c3e3]"><div className="relative flex h-28 items-center justify-center bg-[#f2edf8]"><span className="absolute left-3 top-3 rounded bg-white/75 px-2 py-1 text-[8px] font-semibold text-[#9a82b3]">CUSTOMER SUPPORT</span><div className="mt-3 flex items-center gap-3"><span className="rounded-full bg-[#e4daef] p-3 text-[#a089bb]"><Headphones size={26}/></span><div className="rotate-[-3deg] rounded-xl rounded-bl-none bg-white px-4 py-3 text-[11px] leading-relaxed text-[#91829e]">“They paid… so why does<br/> the invoice say unpaid?”<span className="ml-2 text-[#b8a8c9]">•••</span></div></div></div><div className="p-4"><div className="flex items-center justify-between"><h3 className="text-sm font-bold">The customer called.</h3><ArrowUpRight size={16} className="text-[#b7a5c5]"/></div><p className="mt-2 text-[11px] leading-relaxed text-[#9295a4]">Ask the right questions. Find the real issue.<br className="hidden xl:block"/> Be the person who can explain it.</p><div className="mt-4 flex items-center justify-between border-t border-[#f0edf3] pt-3 text-[10px]"><span className="text-[#aa91bd]">{supportCases.length} real-world cases</span><span className="flex items-center gap-1 text-[#999eaa]">Pick up the call <ArrowRight size={12}/></span></div></div></Link></div></section>;
}