import React from 'react';
import { NavLink } from 'react-router-dom';
import { Layers, LayoutDashboard, Route, Zap, Coffee, Headphones, ArrowLeftRight, BookOpen, ArrowUpRight, X } from 'lucide-react';
const groups = [{ label:'YOUR LEARNING', items:[['Overview','/',LayoutDashboard],['Learning path','/path',Route],['Daily workout','/learn?mode=daily',Zap]] },{label:'PUT IT INTO PRACTICE',items:[['Maple Coffee Co.','/business',Coffee],['The customer called','/support',Headphones],['Tally vs QuickBooks','/software',ArrowLeftRight]]},{label:'YOUR TOOLKIT',items:[['Terminology bridge','/glossary',BookOpen]]}];
export default function Sidebar({ open, onClose }) {
 return <><button aria-label="Close navigation" onClick={onClose} className={`${open?'block':'hidden'} fixed inset-0 z-30 bg-black/25 lg:hidden`} /><aside className={`${open?'translate-x-0':'-translate-x-full'} fixed inset-y-0 left-0 z-40 flex w-[238px] flex-col border-r border-[#e8e9f0] bg-[#fdfdfe] px-5 py-8 transition-transform lg:translate-x-0`}>
  <NavLink to="/" onClick={onClose} className="mb-11 flex items-center gap-2.5 px-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#7560d6] text-white"><Layers size={21}/></span><span className="text-[23px] font-bold tracking-tight">ledger<span className="text-[#806bda]">ly</span><span className="text-[#a598d4]">.</span></span></NavLink>
  <button onClick={onClose} aria-label="Close menu" className="absolute right-3 top-3 lg:hidden"><X size={18}/></button>
  <div className="space-y-8">{groups.map(group=><div key={group.label}><p className="eyebrow mb-3 px-3 text-[9px]">{group.label}</p><nav className="space-y-1">{group.items.map(([name,to,Icon])=><NavLink key={to} end={to==='/'} to={to} onClick={onClose} className={({isActive})=>`flex items-center gap-3 rounded-lg px-3 py-3 text-[12px] font-medium ${isActive?'bg-[#eeeafb] text-[#7761cb]':'text-[#7f8194] hover:bg-[#f6f5fa]'}`}><Icon size={17} strokeWidth={1.7}/>{name}{name==='Daily workout'&&<span className="ml-auto h-1.5 w-1.5 rounded-full bg-[#edb45b]"/>}</NavLink>)}</nav></div>)}</div>
  <div className="mt-auto pt-8"><div className="rounded-xl border border-[#e9e3f4] bg-[#f5f2fb] p-4"><div className="mb-2 flex items-center justify-between"><span className="text-lg">✦</span><span className="eyebrow text-[#a69abd]">THE BIG PICTURE</span></div><p className="text-xs font-semibold leading-relaxed">Don’t just learn the buttons.<br/>Understand the books.</p><NavLink to="/path" onClick={onClose} className="mt-3 flex items-center gap-1 text-[11px] font-semibold text-[#8066cb]">Your journey to consultant <ArrowUpRight size={13}/></NavLink></div><p className="mt-5 px-3 text-[10px] text-[#b0b1bd]">A little practice. A lot of possibility.</p></div>
 </aside></>;
}