import React,{useState} from 'react';
import { SlidersHorizontal, RotateCcw } from 'lucide-react';
import FinancialTable from '@/components/accounting/FinancialTable';
import { money } from '@/components/accounting/accountingData';
const initial={sales:10000,unpaid:70,stock:5000,supplierCredit:60,loan:0,equipment:2000};
const controls=[['sales','Sales earned',0,20000,500],['unpaid','Sales still unpaid (%)',0,100,10],['stock','Inventory purchased',4000,12000,500],['supplierCredit','Purchases still unpaid (%)',0,100,10],['loan','New business loan',0,10000,500],['equipment','Equipment bought for cash',0,10000,500]];
export default function StatementPlayground(){
 const [values,setValues]=useState(initial);const {sales,unpaid,stock,supplierCredit,loan,equipment}=values;
 const cogs=sales*.2,ar=sales*unpaid/100,ap=stock*supplierCredit/100,inventory=stock-cogs,profit=sales-cogs-2000,operating=sales-ar-(stock-ap)-2000,cash=10000+operating-equipment+loan,assets=cash+ar+inventory+equipment;
 return <div className="space-y-5"><div className="rounded-xl bg-[#f2edf8] p-5"><div className="flex items-center justify-between gap-3"><h3 className="flex items-center gap-2 font-bold"><SlidersHorizontal size={18}/>Profitable. But where’s the cash?</h3><button aria-label="Reset statement experiment" onClick={()=>setValues(initial)} className="secondary-btn !p-2"><RotateCcw size={14}/></button></div><p className="muted mt-3">Standalone experiment—not your saved Maple books. Change one lever and watch all three statements respond. Opening cash and owner capital are $10,000; operating costs are $2,000 cash; goods sold cost 20% of sales.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{controls.map(([key,label,min,max,step])=><label className="panel p-4" key={key}><span className="flex justify-between gap-2 text-xs"><span className="text-[#a28bae]">{label}</span><b>{key==='unpaid'||key==='supplierCredit'?`${values[key]}%`:money(values[key])}</b></span><input type="range" min={min} max={max} step={step} value={values[key]} onChange={e=>setValues({...values,[key]:Number(e.target.value)})} className="mt-5 w-full accent-[#a084c0]"/></label>)}</div><div className="grid gap-4 lg:grid-cols-3"><FinancialTable title="Income statement" rows={[["Revenue",sales],['Cost of goods sold',cogs],['Operating expenses',2000]]} total={profit} label="Net income"/><FinancialTable title="Balance sheet" rows={[["Cash (negative = funding gap)",cash],['Receivables',ar],['Inventory',inventory],['Equipment',equipment],['Total assets',assets],['Payables',ap],['Loan',loan],['Capital + current earnings',10000+profit]]} total={ap+loan+10000+profit} label="Liabilities + equity"/><FinancialTable title="Cash flow" rows={[["Operating",operating],['Investing',-equipment],['Financing',loan],['Opening cash',10000]]} total={cash} label="Closing cash"/></div><div role="status" className={`rounded-xl p-5 text-sm leading-relaxed ${profit>0&&cash<0?'bg-[#fff0e1] text-[#a1794e]':'bg-[#eaf4ed] text-[#7c9c82]'}`}>{profit>0&&cash<0?'Profitable, but out of cash: ':''}Net income is {money(profit)}, but {money(ar)} of sales remains uncollected and {money(inventory)} is tied up in stock. Paying for equipment uses cash without being a full immediate expense; a loan brings cash without creating revenue.</div><p className="text-[10px] leading-relaxed text-[#a99bb2]">Accrual accounting illustration · No sales tax, depreciation, interest, or opening receivables/payables. A negative cash result indicates additional financing or changed payment timing is needed, not that a bank automatically permits an overdraft.</p></div>;
}