import React,{useState} from 'react';
import { MessageCircle, ArrowRight, CheckCircle2 } from 'lucide-react';
import { useLearning } from '@/components/accounting/LearningProvider';
import useSavedActivity from '@/components/accounting/useSavedActivity';
import ProgressSaveStatus from '@/components/accounting/ProgressSaveStatus';
export default function SupportConversation({scenario}){
 const {saveAttempt}=useLearning();
 const checkpoint=useSavedActivity(`support:${scenario.id}`,()=>({asked:[],phase:0,diagnosis:null,explanation:null}));
 const {asked,phase,diagnosis,explanation}=checkpoint.state;
 const setAsked=asked=>checkpoint.update({asked}),setPhase=phase=>checkpoint.update({phase}),setDiagnosis=diagnosis=>checkpoint.update({diagnosis}),setExplanation=explanation=>checkpoint.update({explanation});
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 const quality=asked.reduce((s,i)=>s+scenario.questions[i].quality,0), relevant=asked.filter(i=>scenario.questions[i].quality>0).length,irrelevant=asked.length-relevant;
 const correct=diagnosis===scenario.correct;const scores=[['Accounting knowledge',correct?100:30],['Diagnostic reasoning',correct?Math.min(100,relevant*35):20],['Question quality',Math.max(0,Math.min(100,quality*15)-irrelevant*20)],['Software understanding',correct&&relevant>=2?100:40],['Explaining the solution',explanation===scenario.explainCorrect?100:20]];
 const finish=async()=>{if(busy)return;setBusy(true);setError('');try{await saveAttempt({attempt_key:checkpoint.state.run_id,activity_id:scenario.id,kind:'support',topic:'Troubleshooting',score:Math.round(scores.reduce((s,[,n])=>s+n,0)/5),mistakes:(correct?0:1)+(explanation===scenario.explainCorrect?0:1)});await checkpoint.update({phase:3});}catch(e){setError(e.message||'Could not save. Try again.');}finally{setBusy(false);}};
 return <div className="space-y-5"><ProgressSaveStatus status={checkpoint.status} error={checkpoint.error} retry={checkpoint.retry}/><div className="panel p-5"><p className="eyebrow mb-2">{scenario.customer} · {scenario.business}</p><p className="text-lg leading-relaxed">“{scenario.complaint}”</p></div>{asked.map(i=><div key={i} className="space-y-3"><p className="ml-8 rounded-xl rounded-br-none bg-[#ebe5f5] p-4 text-sm text-[#89739e]">You: {scenario.questions[i].text}</p><p className="mr-8 rounded-xl rounded-bl-none border border-[#e9e4ee] bg-white p-4 text-sm leading-relaxed text-[#93839f]">{scenario.customer}: {scenario.questions[i].answer}</p></div>)}
 {phase===0&&<div className="panel p-5"><h3 className="mb-4 text-sm font-bold">What would you ask first?</h3><div className="space-y-2">{scenario.questions.map((q,i)=>!asked.includes(i)&&<button key={i} onClick={()=>setAsked([...asked,i])} className="flex w-full items-center gap-3 rounded-lg border border-[#e9e3ef] p-3 text-left text-sm text-[#9883aa] hover:bg-[#faf7fd]"><MessageCircle size={15}/>{q.text}</button>)}</div><button onClick={()=>setPhase(1)} disabled={!asked.length} className="primary-btn mt-5">I’m ready to diagnose <ArrowRight size={14}/></button></div>}
 {phase===1&&<div className="panel p-5"><h3 className="mb-4 font-bold">What is the most likely root cause?</h3>{scenario.diagnoses.map((d,i)=><button key={i} onClick={()=>setDiagnosis(i)} className={`mb-3 w-full rounded-xl border p-4 text-left text-sm ${diagnosis===i?'border-[#b69bd4] bg-[#eee7f8]':'border-[#e5dfeb]'}`}>{d}</button>)}<div className="flex flex-wrap gap-3"><button className="secondary-btn" onClick={()=>setPhase(0)}>Ask another question</button><button className="primary-btn" disabled={diagnosis===null} onClick={()=>setPhase(2)}>Reveal the accounting logic</button></div></div>}
 {phase>=2&&<><div className={`rounded-xl p-5 ${correct?'bg-[#edf5ee] text-[#688a6f]':'bg-[#fff4e6] text-[#9e8155]'}`}><h3 className="font-bold">{correct?'You found the root cause.':'Let’s separate the symptom from the cause.'}</h3><p className="mt-3 text-sm">You chose: {scenario.diagnoses[diagnosis]}.</p><p className="mt-2 text-sm"><b>Correct diagnosis:</b> {scenario.diagnoses[scenario.correct]}.</p><p className="mt-3 text-sm leading-relaxed">{scenario.reason}</p></div><div className="panel space-y-3 p-5"><p className="eyebrow">THE CORRECTION PLAN</p><p className="text-sm leading-relaxed text-[#97869f]">{scenario.fix}</p><p className="rounded-xl bg-[#f6f3fa] p-4 text-xs leading-relaxed text-[#9c87b0]">{scenario.software}</p></div></>}
 {phase===2&&<div className="panel p-5"><h3 className="mb-4 font-bold">Now explain it to the customer.</h3>{scenario.explanations.map((e,i)=><button key={i} onClick={()=>setExplanation(i)} className={`mb-3 w-full rounded-xl border p-4 text-left text-sm leading-relaxed ${explanation===i?'border-[#b69bd4] bg-[#eee7f8]':'border-[#e5dfeb]'}`}>{e}</button>)}<button onClick={finish} className="primary-btn" disabled={explanation===null||busy||checkpoint.status==='saving'||checkpoint.status==='error'}>{busy?'Saving case…':'Finish the call'}</button></div>}
 {phase===3&&checkpoint.status==='saved'&&<div className="panel p-6"><h3 className="flex items-center gap-2 text-lg font-bold"><CheckCircle2 size={20} className="text-[#83ac8d]"/>Case reviewed. Progress saved.</h3><p className="muted mt-3">{explanation===scenario.explainCorrect?'Your explanation connects the accounting issue to a safe, understandable correction.':`Your explanation missed the accounting cause. Better: ${scenario.explanations[scenario.explainCorrect]}`}</p><div className="mt-5 space-y-4">{scores.map(([name,n])=><div key={name}><div className="mb-2 flex justify-between text-xs"><span>{name}</span><span>{n}%</span></div><div className="h-2 rounded-full bg-[#f0ebf5]"><div className="h-full rounded-full bg-[#ac95c6]" style={{width:`${n}%`}}/></div></div>)}</div><p className="mt-4 text-[11px] leading-relaxed text-[#a697b1]">Rubric: correct cause, relevant evidence, useful questions, workflow understanding, and a clear explanation. Asking unrelated questions lowers question quality; choosing a cause without enough evidence lowers diagnostic reasoning.</p></div>}{error&&<p role="alert" className="text-sm text-rose-600">{error}</p>}</div>;
}