import React,{useState} from 'react';
import { ArrowRight } from 'lucide-react';
import JournalTable from '@/components/accounting/JournalTable';
import { money, summarize } from '@/components/accounting/accountingData';
const stages=['Source','Journal','Ledger','Trial balance','Adjustments','Income statement','Balance sheet','Cash flow'];
export default function TransactionFlow({lesson}){
 const [stage,setStage]=useState(0); const totals=summarize([{lines:lesson.journal}]);const b=totals.balances;
 const cashLine=lesson.journal.find(l=>l.account==='Cash'),cash=cashLine?cashLine.debit-cashLine.credit:0;
 const category=lesson.journal.some(l=>['Owner capital','Loan payable'].includes(l.account))?'Financing':lesson.journal.some(l=>l.account==='Equipment')?'Investing':'Operating';
 return <div className="space-y-5"><div><h2 className="text-xl font-bold">Follow the transaction.</h2><p className="muted mt-2">Same event. Different lenses. Tap a stage to see where it goes.</p></div><div className="flex flex-wrap items-center gap-2">{stages.map((name,i)=><React.Fragment key={name}><button onClick={()=>setStage(i)} className={`rounded-lg border px-3 py-2 text-[11px] ${stage===i?'border-[#b8a8e5] bg-[#eee9fa] font-semibold text-[#8167c2]':'border-[#ededf3] bg-white text-[#9690a1]'}`}>{i+1}. {name}</button>{i<7&&<ArrowRight size={12} className="text-[#c8c0d5]"/>}</React.Fragment>)}</div>
 {stage===0&&<div className="panel p-6"><p className="eyebrow mb-3">SOURCE TRANSACTION</p><p className="text-lg leading-relaxed">{lesson.scenario}</p><p className="muted mt-4">Keep the supporting invoice, bill, receipt, or bank record. The source proves what happened; it is not a second posting.</p></div>}
 {stage===1&&<JournalTable lines={lesson.journal}/>}
 {stage===2&&<div className="grid gap-3 sm:grid-cols-2">{lesson.journal.map(l=><div key={l.account} className="panel p-4"><p className="border-b-2 pb-2 text-center text-sm font-bold">{l.account}</p><div className="grid grid-cols-2 divide-x pt-3 text-center text-xs"><div><p className="mb-3 text-[#a29bab]">Debit</p>{l.debit?money(l.debit):'—'}</div><div><p className="mb-3 text-[#a29bab]">Credit</p>{l.credit?money(l.credit):'—'}</div></div></div>)}</div>}
 {stage===3&&<div><JournalTable lines={lesson.journal} title="Trial balance · this transaction’s contribution"/><p className="muted mt-3">A complete trial balance aggregates every ledger balance. Equal totals do not guarantee the accounts or dates are correct.</p></div>}
 {stage===4&&<div className="panel p-6"><h3 className="font-semibold">Does anything need adjusting?</h3><p className="muted mt-3">No additional adjustment is assumed in this isolated event. At period-end, check depreciation, accrued costs, prepayments, stock losses, and tax. Adjustments must have evidence—not just make a total look right.</p>{lesson.id==='equipment'&&<p className="mt-4 text-sm text-[#8a70b5]">For example, depreciation later moves part of the laptop’s cost to expense over its useful life. Buying it and depreciating it are different entries.</p>}</div>}
 {stage===5&&<div className="panel space-y-4 p-6">{[['Revenue change',totals.revenue],['Expense change',totals.expenses],['Net income change',totals.profit]].map(([k,v])=><div key={k} className="flex justify-between border-b pb-3 text-sm"><span>{k}</span><b>{money(v)}</b></div>)}<p className="muted">Accrual basis · this entry only, not the full business.</p></div>}
 {stage===6&&<div className="panel p-6"><div className="grid gap-4 sm:grid-cols-3">{[['Assets',totals.assets],['Liabilities',totals.liabilities],['Equity including profit',totals.equity]].map(([k,v])=><div key={k} className="rounded-xl bg-[#f7f5fb] p-4"><p className="text-xs text-[#8d839e]">{k}</p><p className="mt-2 text-xl font-bold">{money(v)}</p></div>)}</div><p className="muted mt-4">Changes balance: assets = liabilities + equity. Profit flows into equity; it is not another cash account.</p></div>}
 {stage===7&&<div className="panel p-6"><p className="eyebrow">{category.toUpperCase()} CASH FLOW</p><p className="my-4 text-4xl font-bold">{money(cash)}</p><p className="muted">{cash?'Only the actual cash movement appears here. The rest of the entry explains what the cash movement means.':'No cash moved. A credit purchase or an unpaid invoice can change the balance sheet without appearing as a cash inflow or outflow.'}</p></div>}
 </div>;
}