import React,{useState} from 'react';
import { Coffee, ArrowRight, CheckCircle2, BookOpen } from 'lucide-react';
import { useLearning } from '@/components/accounting/LearningProvider';
import { businessEvents,summarize,money } from '@/components/accounting/accountingData';
import JournalBuilder from '@/components/accounting/JournalBuilder';
import BusinessReports from '@/components/accounting/BusinessReports';
import JournalTable from '@/components/accounting/JournalTable';
import TransactionFlow from '@/components/accounting/TransactionFlow';
export default function Business(){
 const {transactions,postTransaction}=useLearning();const [tab,setTab]=useState('run'),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState(null);
 const next=businessEvents.find(e=>!transactions.some(t=>t.event_key===e.event_key)),s=summarize(transactions),day=transactions.at(-1)?.day||0;
 const lesson=next?{id:next.event_key,journal:next.lines,tally:'Choose the voucher that represents the event, then verify the affected ledgers and any bill allocation.',quickbooks:'Use the matching invoice, bill, sales receipt, expense, or payment workflow. Pay an existing bill rather than creating a second expense.',problem:'When a report looks wrong, inspect both the account classification and the transaction direction. A balanced entry can still describe the wrong event.',principle:'Recognize what the business received, used, earned, or owes. Debits equal credits; paying a previously recorded bill settles a liability rather than creating a second expense.',explanation:next.lines.map(l=>`${l.account}: ${l.debit?'debit':'credit'} ${money(l.debit+l.credit)}`).join('. ')}:null;
 const post=async()=>{if(busy||!ready||!next)return;setBusy(true);setError('');try{await postTransaction(next);setSelected(next);setReady(false);}catch(e){setError(e.message||'Could not post the transaction. Please try again.');}finally{setBusy(false);}};
 return <div className="page-enter space-y-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="eyebrow">YOUR REAL-BUSINESS PLAYGROUND</p><h1 className="page-title mt-3 flex items-center gap-3"><Coffee className="text-[#8faf94]" size={31}/>Maple Coffee Co.</h1><p className="muted mt-3">90 days. 18 key moments. Every decision leaves a trail in the books.</p></div><span className="rounded-full bg-[#eaf3ec] px-4 py-2 text-xs font-semibold text-[#82a78e]">Day {day} / 90</span></div><div className="h-1.5 rounded-full bg-[#e5eee7]"><div className="h-full rounded-full bg-[#92b69b] transition-all" style={{width:`${day/90*100}%`}}/></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[['Cash in bank',s.balances.Cash],['Net income',s.profit],['Customers owe you',s.balances['Accounts receivable']],['You owe vendors',-s.balances['Accounts payable']]].map(([label,n])=><div key={label} className="panel p-4"><p className="text-[10px] text-[#a0a297]">{label}</p><p className="mt-2 text-2xl font-bold">{money(n)}</p></div>)}</div><div className="flex gap-3"><button onClick={()=>setTab('run')} className={tab==='run'?'primary-btn':'secondary-btn'}>Run the business</button><button onClick={()=>setTab('reports')} className={tab==='reports'?'primary-btn':'secondary-btn'}><BookOpen size={15}/>Open the books</button></div>
 {tab==='reports'?<BusinessReports transactions={transactions}/>:<div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_310px]"><div className="space-y-5">{next?<><div className="rounded-xl border border-[#d9e7dc] bg-[#eff5f0] p-6"><p className="eyebrow text-[#93a893]">DAY {next.day} · YOUR NEXT TRANSACTION</p><h2 className="mt-3 text-xl font-bold leading-relaxed">{next.description}</h2><p className="mt-3 text-xs leading-relaxed text-[#99a591]">Build the correct entry, then post it. Your ledger and every report will update together.</p></div><div className="panel p-5"><JournalBuilder key={next.event_key} lesson={lesson} onSolved={()=>setReady(true)} onMistake={()=>setReady(false)}/><button className="primary-btn mt-6" disabled={!ready||busy} onClick={post}>{busy?'Posting…':'Post to Maple’s books'}<ArrowRight size={14}/></button>{error&&<p role="alert" className="mt-3 text-sm text-rose-600">{error}</p>}</div></>:<div className="panel p-8"><CheckCircle2 className="mb-4 text-[#89b496]" size={34}/><h2 className="text-2xl font-bold">Your first 90 days, accounted for.</h2><p className="muted mt-3">All 18 milestones are posted. Open the books to follow every dollar, review overdue invoices, and see how profit differs from cash.</p><button onClick={()=>setTab('reports')} className="primary-btn mt-5">Review the final books</button></div>}{selected&&<div className="panel p-5"><p className="eyebrow mb-4">TRANSACTION SPOTLIGHT · DAY {selected.day}</p><TransactionFlow key={selected.event_key} lesson={{id:selected.event_key,scenario:selected.description,journal:selected.lines}}/><p className="mt-4 rounded-lg bg-[#f6f2fa] p-4 text-xs leading-relaxed text-[#9985aa]">{selected.software||'Tally uses the relevant Sales, Purchase, Receipt, Payment, or Journal voucher. QuickBooks uses the corresponding sales receipt, invoice, bill, payment, or expense. Existing invoices and bills must be settled, not recorded again. The entry above is the accounting result to verify.'}</p></div>}</div><aside className="panel p-5"><h3 className="mb-4 text-sm font-bold">The story so far <span className="ml-1 font-normal text-[#aaa5b1]">({transactions.length})</span></h3>{transactions.length?transactions.slice().reverse().map(t=><button key={t.id} onClick={()=>setSelected(t)} className={`mb-3 w-full rounded-xl border p-3 text-left ${selected?.event_key===t.event_key?'border-[#bfb0d2] bg-[#f4eff9]':'border-[#eeeaf2] hover:bg-[#faf8fc]'}`}><span className="text-[9px] font-semibold text-[#a398ad]">DAY {t.day}</span><p className="mt-1 text-[11px] leading-relaxed text-[#978c9f]">{t.description}</p></button>):<p className="text-xs leading-relaxed text-[#aaa0b1]">An empty ledger. A fresh start. Post your first transaction to start the story.</p>}</aside></div>}
 <p className="text-[10px] leading-relaxed text-[#aaa4b0]">Simplified CAD simulation: tax is omitted unless explicitly stated; payroll deductions are illustrative, employer contributions and depreciation are excluded. All coffee bags cost $10. This is an accounting logic exercise, not a complete tax-compliant set of books.</p></div>;
}