import React,{useState} from 'react';
import { Coffee, ArrowRight, CheckCircle2, BookOpen, CalendarClock, Lock } from 'lucide-react';
import { useLearning } from '@/components/accounting/LearningProvider';
import { allEvents,businessEvents,operatingDays,summarize,money } from '@/components/accounting/accountingData';
import JournalBuilder from '@/components/accounting/JournalBuilder';
import BusinessReports from '@/components/accounting/BusinessReports';
import TransactionFlow from '@/components/accounting/TransactionFlow';
const phaseOf = e => e.phase || 'Operations';
const phaseCopy = {
 Operations:{eyebrow:e=>`DAY ${e.day} · YOUR NEXT TRANSACTION`,hint:'Build the correct entry, then post it. Your ledger and every report will update together.',Icon:Coffee,tone:'border-[#d9e7dc] bg-[#eff5f0]',label:'text-[#93a893]',body:'text-[#99a591]'},
 'Year-end':{eyebrow:()=>'QUARTER END · ADJUSTING ENTRY',hint:'Nothing happened at the bank today. These entries record what happened to value: what was used up, what is owed, and what the count actually found.',Icon:CalendarClock,tone:'border-[#e3ddc8] bg-[#faf7ec]',label:'text-[#a8954f]',body:'text-[#a2946e]'},
 Close:{eyebrow:()=>'CLOSING THE BOOKS',hint:'Revenue and expenses measure one period only. Emptying them into equity is what lets the next quarter start from zero.',Icon:Lock,tone:'border-[#ddd8ea] bg-[#f5f2fb]',label:'text-[#8f7fb5]',body:'text-[#978bab]'}
};
export default function Business(){
 const {transactions,postTransaction}=useLearning();
 const [tab,setTab]=useState('run'),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState(null);
 const posted=new Set(transactions.map(t=>t.event_key));
 const next=allEvents.find(e=>!posted.has(e.event_key));
 const s=summarize(transactions);
 const operatingPosted=businessEvents.filter(e=>posted.has(e.event_key)).length;
 const day=Math.min(operatingDays,businessEvents[Math.max(0,operatingPosted-1)]?.day||0);
 const phase=next?phaseOf(next):'Done';
 const copy=phaseCopy[phase]||phaseCopy.Operations;
 const lesson=next?{id:next.event_key,journal:next.lines,principle:next.note||'Ask what Maple received, used up, earned, or now owes — then decide whether each account went up or down. Paying a bill recorded earlier settles a liability; it does not create a second expense.'}:null;
 const post=async()=>{if(busy||!ready||!next)return;setBusy(true);setError('');try{await postTransaction({event_key:next.event_key,day:next.day,description:next.description,cash_category:next.cash_category,phase:next.phase,party:next.party,inventory_units:next.inventory_units,software:next.software,lines:next.lines.map(({account,debit,credit})=>({account,debit,credit}))});setSelected(next);setReady(false);}catch(e){setError(e.message||'Could not post the transaction. Please try again.');}finally{setBusy(false);}};
 return <div className="page-enter space-y-6">
 <div className="flex flex-wrap items-center justify-between gap-4"><div><p className="eyebrow">YOUR REAL-BUSINESS PLAYGROUND</p><h1 className="page-title mt-3 flex items-center gap-3"><Coffee className="text-[#8faf94]" size={31}/>Maple Coffee Co.</h1><p className="muted mt-3">{operatingDays} days of trading, then a full quarter end: {allEvents.length} entries from the first deposit to a closed set of books.</p></div><span className="rounded-full bg-[#eaf3ec] px-4 py-2 text-xs font-semibold text-[#82a78e]">{transactions.length} of {allEvents.length} posted</span></div>
 <div><div className="h-1.5 rounded-full bg-[#e5eee7]"><div className="h-full rounded-full bg-[#92b69b] transition-all" style={{width:`${transactions.length/allEvents.length*100}%`}}/></div><div className="mt-2 flex justify-between text-[10px] text-[#a3ada4]"><span>Day {day} of {operatingDays} · trading</span><span>Quarter end · adjust &amp; close</span></div></div>
 <div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[['Cash in bank',s.balances.Cash],['Result this period',s.profit],['Customers owe you',s.balances['Accounts receivable']],['You owe vendors',-s.balances['Accounts payable']]].map(([label,n])=><div key={label} className="panel p-4"><p className="text-[10px] text-[#a0a297]">{label}</p><p className="mt-2 text-2xl font-bold">{money(n)}</p></div>)}</div>
 <div className="flex gap-3"><button onClick={()=>setTab('run')} className={tab==='run'?'primary-btn':'secondary-btn'}>Run the business</button><button onClick={()=>setTab('reports')} className={tab==='reports'?'primary-btn':'secondary-btn'}><BookOpen size={15}/>Open the books</button></div>
 {tab==='reports'?<BusinessReports transactions={transactions}/>:<div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_310px]"><div className="space-y-5">{next?<>
  <div className={`rounded-xl border p-6 ${copy.tone}`}><p className={`eyebrow ${copy.label}`}><copy.Icon size={13} className="mr-1.5 inline"/>{copy.eyebrow(next)}</p><h2 className="mt-3 text-xl font-bold leading-relaxed">{next.description}</h2><p className={`mt-3 text-xs leading-relaxed ${copy.body}`}>{copy.hint}</p>{next.note&&<p className={`mt-2 text-xs leading-relaxed ${copy.body}`}>{next.note}</p>}</div>
  <div className="panel p-5"><JournalBuilder key={next.event_key} lesson={lesson} onSolved={()=>setReady(true)} onMistake={()=>setReady(false)}/><button className="primary-btn mt-6" disabled={!ready||busy} onClick={post}>{busy?'Posting…':'Post to Maple’s books'}<ArrowRight size={14}/></button>{error&&<p role="alert" className="mt-3 text-sm text-rose-600">{error}</p>}</div></>:
  <div className="panel p-8"><CheckCircle2 className="mb-4 text-[#89b496]" size={34}/><h2 className="text-2xl font-bold">A full cycle, start to close.</h2><p className="muted mt-3">All {allEvents.length} entries are posted: {businessEvents.length} trading days, {allEvents.length-businessEvents.length-3} quarter-end adjustments and the closing entries. Open the books to compare the unadjusted, adjusted and post-closing trial balances — the clearest picture of what adjusting entries actually do.</p><button onClick={()=>setTab('reports')} className="primary-btn mt-5">Review the final books</button></div>}
  {selected&&<div className="panel p-5"><p className="eyebrow mb-4">SPOTLIGHT · {phaseOf(selected)==='Operations'?`DAY ${selected.day}`:phaseOf(selected)==='Close'?'CLOSING':'QUARTER END'}</p><TransactionFlow key={selected.event_key} lesson={{id:selected.event_key,scenario:selected.description,journal:selected.lines}}/><p className="mt-4 rounded-lg bg-[#f6f2fa] p-4 text-xs leading-relaxed text-[#9985aa]">{selected.software||(phaseOf(selected)==='Operations'?'Tally uses the relevant Sales, Purchase, Receipt, Payment, or Journal voucher. QuickBooks uses the corresponding sales receipt, invoice, bill, payment, or expense. Existing invoices and bills must be settled, not recorded again. The entry above is the accounting result to verify.':'Both Tally and QuickBooks post period-end adjustments as journal entries, and both carry the result into equity automatically at year-end rather than asking you to write the closing entry. Building it by hand once is how you know what the software did.')}</p></div>}</div>
  <aside className="panel p-5"><h3 className="mb-4 text-sm font-bold">The story so far <span className="ml-1 font-normal text-[#aaa5b1]">({transactions.length})</span></h3>{transactions.length?transactions.slice().reverse().map(t=><button key={t.id} onClick={()=>setSelected(t)} className={`mb-3 w-full rounded-xl border p-3 text-left ${selected?.event_key===t.event_key?'border-[#bfb0d2] bg-[#f4eff9]':'border-[#eeeaf2] hover:bg-[#faf8fc]'}`}><span className="text-[9px] font-semibold text-[#a398ad]">{phaseOf(t)==='Operations'?`DAY ${t.day}`:phaseOf(t)==='Close'?'CLOSING':'QUARTER END'}</span><p className="mt-1 text-[11px] leading-relaxed text-[#978c9f]">{t.description}</p></button>):<p className="text-xs leading-relaxed text-[#aaa0b1]">An empty ledger. A fresh start. Post your first transaction to start the story.</p>}</aside></div>}
 <p className="text-[10px] leading-relaxed text-[#aaa4b0]">Simplified CAD simulation: sales tax is omitted unless a transaction states it; payroll deductions are illustrative and employer contributions are excluded. All coffee bags cost $10, and interest uses a 360-day basis. This is an accounting logic exercise, not a complete tax-compliant set of books.</p></div>;
}
