import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Clock3, Play, Check, Sprout, ArrowUpRight, Zap, ArrowLeftRight } from 'lucide-react';
import { useLearning } from '@/components/accounting/LearningProvider';
import { lessons } from '@/components/accounting/lessonData';
import DashboardStats from '@/components/accounting/DashboardStats';
import BrainCard from '@/components/accounting/BrainCard';
import PracticeCards from '@/components/accounting/PracticeCards';
import FlowIllustration from '@/components/accounting/FlowIllustration';
export default function Dashboard(){
 const {user,completed}=useLearning(); const next=lessons.find(l=>!completed.includes(l.id))||lessons[0];const name=user?.full_name?.split(' ')[0];
 return <div className="page-enter space-y-7"><div className="flex flex-wrap items-end justify-between gap-4"><div className="space-y-2"><p className="eyebrow text-[#aaa1bc]">SMALL STEPS. REAL UNDERSTANDING.</p><h1 className="page-title">{completed.length?'Welcome back':'Welcome to your next chapter'}{name?`, ${name}`:''}<span className="text-[#a48cd0]">.</span></h1><p className="muted">Let’s make sense of the numbers behind the business.</p></div><Link to="/path" className="flex items-center gap-2 rounded-full border border-[#e4deef] bg-[#f4f0fa] px-3 py-2 text-[10px] text-[#9e89ba]"><Sprout size={14}/>{completed.length>=6?'LEVEL 2 · PRACTITIONER':'LEVEL 1 · CURIOUS BEGINNER'}</Link></div>
 <DashboardStats/>
 <div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_295px]"><div className="space-y-7">
 <section className="relative overflow-hidden rounded-2xl border border-[#e4d9ef] bg-gradient-to-br from-[#eee5f6] via-[#efe9f8] to-[#f4edf7] p-6 md:p-7"><div className="flex items-center justify-between gap-3"><div className="relative z-10 max-w-[345px]"><span className="rounded-md border border-white/70 bg-white/50 px-2.5 py-1 text-[9px] font-semibold tracking-wider text-[#9b82b4]">PICK UP A LITTLE ACCOUNTING INTUITION</span><h2 className="mt-5 text-[27px] font-bold leading-[1.25] tracking-tight text-[#514566]">{next.id==='equipment'?<>A purchase.<br/>Two changes. One aha!</>:next.title}</h2><p className="mt-3 max-w-[270px] text-xs leading-relaxed text-[#9686a4]">{next.id==='equipment'?'Maple Coffee buys a laptop on credit. What actually changes in the books?':'A real business problem. A decision to make. A new way to understand the books.'}</p><div className="mt-5 flex flex-wrap items-center gap-4"><Link to={`/learn?id=${next.id}`} className="primary-btn !rounded-lg !px-4 !py-2.5 !text-[11px]">{completed.length?'Continue learning':'Let’s figure it out'}<ArrowRight size={14}/></Link><span className="flex items-center gap-1 text-[10px] text-[#a28eaf]"><Clock3 size={12}/>3–5 min · Interactive</span></div></div><FlowIllustration/></div></section>
 <section><div className="mb-4 flex items-center justify-between"><h2 className="text-base font-bold">Your next few aha! moments</h2><Link to="/path" className="flex items-center gap-1 text-[10px] text-[#9b8ab7]">Explore your path <ArrowRight size={12}/></Link></div><div className="panel overflow-hidden">{lessons.slice(0,3).map((lesson,i)=><Link to={`/learn?id=${lesson.id}`} key={lesson.id} className="flex items-center gap-4 border-b border-[#f0f0f6] px-5 py-4 last:border-0 hover:bg-[#fcfaff]"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-full text-xs ${completed.includes(lesson.id)?'bg-[#eaf3ec] text-[#77a684]':i===0?'bg-[#eee7f9] text-[#9b82c6]':'border border-[#eae7f0] text-[#b6adbf]'}`}>{completed.includes(lesson.id)?<Check size={16}/>:String(i+1).padStart(2,'0')}</span><div className="min-w-0 flex-1"><h3 className="text-xs font-semibold">{lesson.title}</h3><p className="mt-1 text-[10px] text-[#a3a0b0]">{lesson.topic} <span className="mx-1.5">·</span> Learn by doing</p></div><span className="hidden rounded bg-[#f7f5fa] px-2 py-1 text-[8px] text-[#aaa0b7] sm:block">{completed.includes(lesson.id)?'MASTERED':'BEGINNER'}</span><Play size={13} className="text-[#b4a4c9]"/></Link>)}</div></section>
 <PracticeCards/>
 <Link to="/software" className="panel flex items-center gap-4 p-4 hover:bg-[#fcfbfe]"><span className="rounded-xl bg-[#f0eef7] p-3 text-[#a092bd]"><ArrowLeftRight size={18}/></span><div className="flex-1"><h3 className="text-xs font-bold">Two interfaces. One accounting engine.</h3><p className="mt-1 text-[10px] text-[#9a97a8]">Connect what you learn to Tally and QuickBooks.</p><div className="mt-2 flex flex-wrap gap-2 text-[9px]"><span className="rounded bg-[#edf4f7] px-2 py-1 text-[#809aaa]">Tally connections: {completed.length}/9</span><span className="rounded bg-[#eef6ef] px-2 py-1 text-[#83a38a]">QuickBooks connections: {completed.length}/9</span></div></div><ArrowRight size={17} className="text-[#ae9dbe]"/></Link>
 </div><div className="space-y-5"><div className="panel p-5"><div className="flex items-center gap-2 text-sm font-bold"><Zap size={17} className="text-[#d5b677]"/> A little better, every day.</div><p className="mt-3 text-xs leading-relaxed text-[#9895a6]">5 small challenges.<br/>One stronger accounting brain.</p><div className="my-4 flex gap-2">{Array.from({length:5},(_,i)=><div key={i} className="grid h-8 flex-1 place-items-center rounded-md border border-[#eee8de] bg-[#fcf9f2] text-[10px] text-[#c5b492]">{i+1}</div>)}</div><Link to="/learn?mode=daily" className="flex items-center justify-between rounded-lg bg-[#f4efe4] px-3 py-2.5 text-[11px] font-semibold text-[#ac9164]">Start today’s workout <ArrowRight size={13}/></Link><p className="mt-3 text-center text-[9px] text-[#b4ac9e]">A small session. No pressure.</p></div><BrainCard/><div className="rounded-xl border border-dashed border-[#ddd6e9] px-5 py-4"><p className="text-[10px] font-semibold text-[#a294b5]">A FRIENDLY REMINDER</p><p className="mt-2 text-xs leading-relaxed text-[#a29bad]">Getting it wrong is part of getting it.<br/>Your next mistake might be your<br/>best lesson yet.</p></div></div></div>
 </div>;
}