import React,{useState} from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, ArrowLeftRight } from 'lucide-react';
import { lessons } from '@/components/accounting/lessonData';
import SoftwareBridge from '@/components/accounting/SoftwareBridge';
import JournalTable from '@/components/accounting/JournalTable';
import TransactionFlow from '@/components/accounting/TransactionFlow';
export default function SoftwareLab(){
 const [index,setIndex]=useState(0),[view,setView]=useState('compare');const lesson=lessons[index];
 return <div className="page-enter mx-auto max-w-5xl"><p className="eyebrow">THE TERMINOLOGY CHANGES. THE LOGIC DOESN’T.</p><h1 className="page-title mt-3">Tally <span className="font-normal text-[#b5a1c9]">↔</span> QuickBooks</h1><p className="muted mt-3">Learn what the software is doing, not just which button to click.</p><div className="my-7 flex flex-wrap gap-2">{lessons.map((l,i)=><button key={l.id} onClick={()=>{setIndex(i);setView('compare');}} className={`rounded-lg border px-4 py-2.5 text-xs ${i===index?'border-[#baa5d5] bg-[#efe8f8] text-[#9675b5]':'border-[#e7e2ed] bg-white text-[#a194ac]'}`}>{l.short}</button>)}</div><div className="panel mb-5 p-6"><p className="eyebrow mb-3">ONE REAL-WORLD TRANSACTION</p><h2 className="text-xl font-semibold leading-relaxed">{lesson.scenario.replace(/Which TWO.*$/,'').replace(/Besides Cash, which TWO.*$/,'')}</h2><div className="mt-4 flex flex-wrap gap-2">{lesson.impact.map(i=><span key={i} className="rounded-full bg-[#f3eff8] px-3 py-1.5 text-[11px] text-[#a18bb4]">{i}</span>)}</div></div><div className="mb-5 flex gap-3"><button className={view==='compare'?'primary-btn':'secondary-btn'} onClick={()=>setView('compare')}>Compare workflows</button><button className={view==='flow'?'primary-btn':'secondary-btn'} onClick={()=>setView('flow')}>Follow the accounting</button></div>{view==='compare'?<div className="space-y-5"><SoftwareBridge lesson={lesson}/><JournalTable lines={lesson.journal} title="The accounting entry underneath"/></div>:<TransactionFlow key={lesson.id} lesson={lesson}/>}<Link to={`/learn?id=${lesson.id}`} className="primary-btn mt-6">Try this transaction yourself <ArrowRight size={15}/></Link><div className="mt-6 rounded-xl border border-[#eee5d3] bg-[#fffaf0] p-4 text-xs leading-relaxed text-[#ab956c]">Canada / India distinction: “sundry debtor,” “sundry creditor,” and “voucher” are common Tally terms. They do not change double-entry principles. Country tax and payroll features are not interchangeable; verify the local edition and configuration.</div></div>;
}